(ns solita.etp.service.energiatodistus-csv-snapshot-test
  (:require [clojure.test :as t]
            [solita.etp.service.energiatodistus-csv :as csv]))

(def ^:private expected-private-columns
  '([:id]
    [:perusparannuspassi-id]
    [:versio]
    [:tila-id]
    [:laatija-id]
    [:laatija-fullname]
    [:allekirjoitusaika]
    [:voimassaolo-paattymisaika]
    [:laskutusaika]
    [:draft-visible-to-paakayttaja]
    [:bypass-validation-limits]
    [:bypass-validation-limits-reason]
    [:korvattu-energiatodistus-id]
    [:korvaava-energiatodistus-id]
    [:laskutettava-yritys-id]
    [:laskuriviviite]
    [:perustiedot :yritys :nimi]
    [:perustiedot :tilaaja]
    [:perustiedot :kieli]
    [:perustiedot :kieli-fi]
    [:perustiedot :kieli-sv]
    [:perustiedot :laatimisvaihe]
    [:perustiedot :laatimisvaihe-fi]
    [:perustiedot :laatimisvaihe-sv]
    [:perustiedot :havainnointikaynti]
    [:perustiedot :uudisrakennus]
    [:perustiedot :havainnointikayntityyppi-id]
    [:perustiedot :havainnointikayntityyppi-fi]
    [:perustiedot :havainnointikayntityyppi-sv]
    [:perustiedot :tayttaa-aplus-vaatimukset]
    [:perustiedot :tayttaa-a0-vaatimukset]
    [:tulokset :laskentatyokalu]
    [:perustiedot :nimi-fi]
    [:perustiedot :nimi-sv]
    [:perustiedot :valmistumisvuosi]
    [:perustiedot :rakennusosa]
    [:perustiedot :katuosoite-fi]
    [:perustiedot :katuosoite-sv]
    [:perustiedot :postinumero]
    [:perustiedot :postitoimipaikka-fi]
    [:perustiedot :postitoimipaikka-sv]
    [:perustiedot :rakennustunnus]
    [:perustiedot :kiinteistotunnus]
    [:perustiedot :paakayttotarkoitus-id]
    [:perustiedot :paakayttotarkoitus-fi]
    [:perustiedot :paakayttotarkoitus-sv]
    [:perustiedot :kayttotarkoitus]
    [:perustiedot :alakayttotarkoitus-fi]
    [:perustiedot :alakayttotarkoitus-sv]
    [:perustiedot :julkinen-rakennus]
    [:tulokset :e-luku]
    [:tulokset :e-luokka]
    [:tulokset :e-luokka-rajat :raja-uusi-2018]
    [:tulokset :e-luokka-rajat :kayttotarkoitus :label-fi]
    [:perustiedot :keskeiset-suositukset-fi]
    [:perustiedot :keskeiset-suositukset-sv]
    [:lahtotiedot :lammitetty-nettoala]
    [:lahtotiedot :rakennusvaippa :ilmanvuotoluku]
    [:lahtotiedot :rakennusvaippa :lampokapasiteetti]
    [:lahtotiedot :rakennusvaippa :ilmatilavuus]
    [:lahtotiedot :rakennusvaippa :ulkoseinat :ala]
    [:lahtotiedot :rakennusvaippa :ulkoseinat :U]
    [:lahtotiedot :rakennusvaippa :ulkoseinat :UA]
    [:lahtotiedot :rakennusvaippa :ulkoseinat :osuus-lampohaviosta]
    [:lahtotiedot :rakennusvaippa :ylapohja :ala]
    [:lahtotiedot :rakennusvaippa :ylapohja :U]
    [:lahtotiedot :rakennusvaippa :ylapohja :UA]
    [:lahtotiedot :rakennusvaippa :ylapohja :osuus-lampohaviosta]
    [:lahtotiedot :rakennusvaippa :alapohja :ala]
    [:lahtotiedot :rakennusvaippa :alapohja :U]
    [:lahtotiedot :rakennusvaippa :alapohja :UA]
    [:lahtotiedot :rakennusvaippa :alapohja :osuus-lampohaviosta]
    [:lahtotiedot :rakennusvaippa :ikkunat :ala]
    [:lahtotiedot :rakennusvaippa :ikkunat :U]
    [:lahtotiedot :rakennusvaippa :ikkunat :UA]
    [:lahtotiedot :rakennusvaippa :ikkunat :osuus-lampohaviosta]
    [:lahtotiedot :rakennusvaippa :ulkoovet :ala]
    [:lahtotiedot :rakennusvaippa :ulkoovet :U]
    [:lahtotiedot :rakennusvaippa :ulkoovet :UA]
    [:lahtotiedot :rakennusvaippa :ulkoovet :osuus-lampohaviosta]
    [:lahtotiedot :rakennusvaippa :kylmasillat-UA]
    [:lahtotiedot :rakennusvaippa :kylmasillat-osuus-lampohaviosta]
    [:lahtotiedot :rakennusvaippa :UA-summa]
    [:lahtotiedot :ikkunat :pohjoinen :ala]
    [:lahtotiedot :ikkunat :pohjoinen :U]
    [:lahtotiedot :ikkunat :pohjoinen :g-ks]
    [:lahtotiedot :ikkunat :koillinen :ala]
    [:lahtotiedot :ikkunat :koillinen :U]
    [:lahtotiedot :ikkunat :koillinen :g-ks]
    [:lahtotiedot :ikkunat :ita :ala]
    [:lahtotiedot :ikkunat :ita :U]
    [:lahtotiedot :ikkunat :ita :g-ks]
    [:lahtotiedot :ikkunat :kaakko :ala]
    [:lahtotiedot :ikkunat :kaakko :U]
    [:lahtotiedot :ikkunat :kaakko :g-ks]
    [:lahtotiedot :ikkunat :etela :ala]
    [:lahtotiedot :ikkunat :etela :U]
    [:lahtotiedot :ikkunat :etela :g-ks]
    [:lahtotiedot :ikkunat :lounas :ala]
    [:lahtotiedot :ikkunat :lounas :U]
    [:lahtotiedot :ikkunat :lounas :g-ks]
    [:lahtotiedot :ikkunat :lansi :ala]
    [:lahtotiedot :ikkunat :lansi :U]
    [:lahtotiedot :ikkunat :lansi :g-ks]
    [:lahtotiedot :ikkunat :luode :ala]
    [:lahtotiedot :ikkunat :luode :U]
    [:lahtotiedot :ikkunat :luode :g-ks]
    [:lahtotiedot :ikkunat :valokupu :ala]
    [:lahtotiedot :ikkunat :valokupu :U]
    [:lahtotiedot :ikkunat :valokupu :g-ks]
    [:lahtotiedot :ikkunat :katto :ala]
    [:lahtotiedot :ikkunat :katto :U]
    [:lahtotiedot :ikkunat :katto :g-ks]
    [:lahtotiedot :ilmanvaihto :tyyppi-id]
    [:lahtotiedot :ilmanvaihto :label-fi]
    [:lahtotiedot :ilmanvaihto :label-sv]
    [:lahtotiedot :ilmanvaihto :kuvaus-fi]
    [:lahtotiedot :ilmanvaihto :kuvaus-sv]
    [:lahtotiedot :ilmanvaihto :paaiv :tulo]
    [:lahtotiedot :ilmanvaihto :paaiv :poisto]
    [:lahtotiedot :ilmanvaihto :paaiv :tulo-poisto]
    [:lahtotiedot :ilmanvaihto :paaiv :sfp]
    [:lahtotiedot :ilmanvaihto :paaiv :lampotilasuhde]
    [:lahtotiedot :ilmanvaihto :paaiv :jaatymisenesto]
    [:lahtotiedot :ilmanvaihto :erillispoistot :tulo]
    [:lahtotiedot :ilmanvaihto :erillispoistot :poisto]
    [:lahtotiedot :ilmanvaihto :erillispoistot :tulo-poisto]
    [:lahtotiedot :ilmanvaihto :erillispoistot :sfp]
    [:lahtotiedot :ilmanvaihto :ivjarjestelma :tulo]
    [:lahtotiedot :ilmanvaihto :ivjarjestelma :poisto]
    [:lahtotiedot :ilmanvaihto :ivjarjestelma :tulo-poisto]
    [:lahtotiedot :ilmanvaihto :ivjarjestelma :sfp]
    [:lahtotiedot :ilmanvaihto :lto-vuosihyotysuhde]
    [:lahtotiedot :ilmanvaihto :tuloilma-lampotila]
    [:lahtotiedot :lammitys :lammitysmuoto-1 :id]
    [:lahtotiedot :lammitys :lammitysmuoto-2 :id]
    [:lahtotiedot :lammitys :lammitysmuoto-label-fi]
    [:lahtotiedot :lammitys :lammitysmuoto-label-sv]
    [:lahtotiedot :lammitys :lammitysmuoto-1 :kuvaus-fi]
    [:lahtotiedot :lammitys :lammitysmuoto-1 :kuvaus-sv]
    [:lahtotiedot :lammitys :lammitysmuoto-2 :kuvaus-fi]
    [:lahtotiedot :lammitys :lammitysmuoto-2 :kuvaus-sv]
    [:lahtotiedot :lammitys :lammonjako :id]
    [:lahtotiedot :lammitys :lammonjako-label-fi]
    [:lahtotiedot :lammitys :lammonjako-label-sv]
    [:lahtotiedot :lammitys :lammonjako :kuvaus-fi]
    [:lahtotiedot :lammitys :lammonjako :kuvaus-sv]
    [:lahtotiedot :lammitys :tilat-ja-iv :tuoton-hyotysuhde]
    [:lahtotiedot :lammitys :tilat-ja-iv :jaon-hyotysuhde]
    [:lahtotiedot :lammitys :tilat-ja-iv :lampokerroin]
    [:lahtotiedot :lammitys :tilat-ja-iv :apulaitteet]
    [:lahtotiedot :lammitys :tilat-ja-iv :lampopumppu-tuotto-osuus]
    [:lahtotiedot :lammitys :tilat-ja-iv :lampohavio-lammittamaton-tila]
    [:lahtotiedot :lammitys :lammin-kayttovesi :tuoton-hyotysuhde]
    [:lahtotiedot :lammitys :lammin-kayttovesi :jaon-hyotysuhde]
    [:lahtotiedot :lammitys :lammin-kayttovesi :lampokerroin]
    [:lahtotiedot :lammitys :lammin-kayttovesi :apulaitteet]
    [:lahtotiedot :lammitys :lammin-kayttovesi :lampopumppu-tuotto-osuus]
    [:lahtotiedot :lammitys :lammin-kayttovesi :lampohavio-lammittamaton-tila]
    [:lahtotiedot :lammitys :takka :maara]
    [:lahtotiedot :lammitys :takka :tuotto]
    [:lahtotiedot :lammitys :ilmalampopumppu :maara]
    [:lahtotiedot :lammitys :ilmalampopumppu :tuotto]
    [:lahtotiedot :jaahdytysjarjestelma :jaahdytyskauden-painotettu-kylmakerroin]
    [:lahtotiedot :lkvn-kaytto :ominaiskulutus]
    [:lahtotiedot :lkvn-kaytto :lammitysenergian-nettotarve]
    [:lahtotiedot :energiankulutuksen-valmius-reagoida-ulkoisiin-signaaleihin]
    [:lahtotiedot :lammitys :lammonjako-lampotilajousto]
    [:lahtotiedot :sis-kuorma :henkilot :kayttoaste]
    [:lahtotiedot :sis-kuorma :henkilot :lampokuorma]
    [:lahtotiedot :sis-kuorma :kuluttajalaitteet :kayttoaste]
    [:lahtotiedot :sis-kuorma :kuluttajalaitteet :lampokuorma]
    [:lahtotiedot :sis-kuorma :valaistus :kayttoaste]
    [:lahtotiedot :sis-kuorma :valaistus :lampokuorma]
    [:tulokset :kaytettavat-energiamuodot :kaukolampo]
    [:tulokset :kaytettavat-energiamuodot :kaukolampo-nettoala]
    [:tulokset :kaytettavat-energiamuodot :kaukolampo-kerroin]
    [:tulokset :kaytettavat-energiamuodot :kaukolampo-kertoimella]
    [:tulokset :kaytettavat-energiamuodot :kaukolampo-nettoala-kertoimella]
    [:tulokset :kaytettavat-energiamuodot :sahko]
    [:tulokset :kaytettavat-energiamuodot :sahko-nettoala]
    [:tulokset :kaytettavat-energiamuodot :sahko-kerroin]
    [:tulokset :kaytettavat-energiamuodot :sahko-kertoimella]
    [:tulokset :kaytettavat-energiamuodot :sahko-nettoala-kertoimella]
    [:tulokset :kaytettavat-energiamuodot :uusiutuva-polttoaine]
    [:tulokset :kaytettavat-energiamuodot :uusiutuva-polttoaine-nettoala]
    [:tulokset :kaytettavat-energiamuodot :uusiutuva-polttoaine-kerroin]
    [:tulokset :kaytettavat-energiamuodot :uusiutuva-polttoaine-kertoimella]
    [:tulokset :kaytettavat-energiamuodot :uusiutuva-polttoaine-nettoala-kertoimella]
    [:tulokset :kaytettavat-energiamuodot :fossiilinen-polttoaine]
    [:tulokset :kaytettavat-energiamuodot :fossiilinen-polttoaine-nettoala]
    [:tulokset :kaytettavat-energiamuodot :fossiilinen-polttoaine-kerroin]
    [:tulokset :kaytettavat-energiamuodot :fossiilinen-polttoaine-kertoimella]
    [:tulokset :kaytettavat-energiamuodot :fossiilinen-polttoaine-nettoala-kertoimella]
    [:tulokset :kaytettavat-energiamuodot :kaukojaahdytys]
    [:tulokset :kaytettavat-energiamuodot :kaukojaahdytys-nettoala]
    [:tulokset :kaytettavat-energiamuodot :kaukojaahdytys-kerroin]
    [:tulokset :kaytettavat-energiamuodot :kaukojaahdytys-kertoimella]
    [:tulokset :kaytettavat-energiamuodot :kaukojaahdytys-nettoala-kertoimella]
    [:tulokset :kaytettavat-energiamuodot :valaistus-kuluttaja-sahko]
    [:tulokset :kaytettavat-energiamuodot :valaistus-kuluttaja-sahko-nettoala]
    [:tulokset :kaytettavat-energiamuodot :muu 0 :nimi]
    [:tulokset :kaytettavat-energiamuodot :muu 0 :ostoenergia]
    [:tulokset :kaytettavat-energiamuodot :muu 0 :muotokerroin]
    [:tulokset :kaytettavat-energiamuodot :muu 0 :ostoenergia-nettoala]
    [:tulokset :kaytettavat-energiamuodot :muu 0 :ostoenergia-kertoimella]
    [:tulokset :kaytettavat-energiamuodot :muu 0 :ostoenergia-nettoala-kertoimella]
    [:tulokset :kaytettavat-energiamuodot :muu 1 :nimi]
    [:tulokset :kaytettavat-energiamuodot :muu 1 :ostoenergia]
    [:tulokset :kaytettavat-energiamuodot :muu 1 :muotokerroin]
    [:tulokset :kaytettavat-energiamuodot :muu 1 :ostoenergia-nettoala]
    [:tulokset :kaytettavat-energiamuodot :muu 1 :ostoenergia-kertoimella]
    [:tulokset :kaytettavat-energiamuodot :muu 1 :ostoenergia-nettoala-kertoimella]
    [:tulokset :kaytettavat-energiamuodot :muu 2 :nimi]
    [:tulokset :kaytettavat-energiamuodot :muu 2 :ostoenergia]
    [:tulokset :kaytettavat-energiamuodot :muu 2 :muotokerroin]
    [:tulokset :kaytettavat-energiamuodot :muu 2 :ostoenergia-nettoala]
    [:tulokset :kaytettavat-energiamuodot :muu 2 :ostoenergia-kertoimella]
    [:tulokset :kaytettavat-energiamuodot :muu 2 :ostoenergia-nettoala-kertoimella]
    [:tulokset :kaytettavat-energiamuodot :summa]
    [:tulokset :kaytettavat-energiamuodot :kertoimella-summa]
    [:tulokset :kasvihuonepaastot]
    [:tulokset :kasvihuonepaastot-nettoala]
    [:tulokset :uusiutuvat-omavaraisenergiat :aurinkosahko]
    [:tulokset :uusiutuvat-omavaraisenergiat :aurinkosahko-nettoala]
    [:tulokset :uusiutuvat-omavaraisenergiat :aurinkolampo]
    [:tulokset :uusiutuvat-omavaraisenergiat :aurinkolampo-nettoala]
    [:tulokset :uusiutuvat-omavaraisenergiat :tuulisahko]
    [:tulokset :uusiutuvat-omavaraisenergiat :tuulisahko-nettoala]
    [:tulokset :uusiutuvat-omavaraisenergiat :lampopumppu]
    [:tulokset :uusiutuvat-omavaraisenergiat :lampopumppu-nettoala]
    [:tulokset :uusiutuvat-omavaraisenergiat :muusahko]
    [:tulokset :uusiutuvat-omavaraisenergiat :muusahko-nettoala]
    [:tulokset :uusiutuvat-omavaraisenergiat :muulampo]
    [:tulokset :uusiutuvat-omavaraisenergiat :muulampo-nettoala]
    [:tulokset :uusiutuvat-omavaraisenergiat 0 :nimi-fi]
    [:tulokset :uusiutuvat-omavaraisenergiat 0 :nimi-sv]
    [:tulokset :uusiutuvat-omavaraisenergiat 0 :vuosikulutus]
    [:tulokset :uusiutuvat-omavaraisenergiat 0 :vuosikulutus-nettoala]
    [:tulokset :uusiutuvat-omavaraisenergiat 1 :nimi-fi]
    [:tulokset :uusiutuvat-omavaraisenergiat 1 :nimi-sv]
    [:tulokset :uusiutuvat-omavaraisenergiat 1 :vuosikulutus]
    [:tulokset :uusiutuvat-omavaraisenergiat 1 :vuosikulutus-nettoala]
    [:tulokset :uusiutuvat-omavaraisenergiat 2 :nimi-fi]
    [:tulokset :uusiutuvat-omavaraisenergiat 2 :nimi-sv]
    [:tulokset :uusiutuvat-omavaraisenergiat 2 :vuosikulutus]
    [:tulokset :uusiutuvat-omavaraisenergiat 2 :vuosikulutus-nettoala]
    [:tulokset :uusiutuvat-omavaraisenergiat 3 :nimi-fi]
    [:tulokset :uusiutuvat-omavaraisenergiat 3 :nimi-sv]
    [:tulokset :uusiutuvat-omavaraisenergiat 3 :vuosikulutus]
    [:tulokset :uusiutuvat-omavaraisenergiat 3 :vuosikulutus-nettoala]
    [:tulokset :uusiutuvat-omavaraisenergiat 4 :nimi-fi]
    [:tulokset :uusiutuvat-omavaraisenergiat 4 :nimi-sv]
    [:tulokset :uusiutuvat-omavaraisenergiat 4 :vuosikulutus]
    [:tulokset :uusiutuvat-omavaraisenergiat 4 :vuosikulutus-nettoala]
    [:tulokset :uusiutuvat-omavaraisenergiat 5 :nimi-fi]
    [:tulokset :uusiutuvat-omavaraisenergiat 5 :nimi-sv]
    [:tulokset :uusiutuvat-omavaraisenergiat 5 :vuosikulutus]
    [:tulokset :uusiutuvat-omavaraisenergiat 5 :vuosikulutus-nettoala]
    [:tulokset :uusiutuvat-omavaraisenergiat-kokonaistuotanto :aurinkosahko]
    [:tulokset :uusiutuvat-omavaraisenergiat-kokonaistuotanto :aurinkolampo]
    [:tulokset :uusiutuvat-omavaraisenergiat-kokonaistuotanto :tuulisahko]
    [:tulokset :uusiutuvat-omavaraisenergiat-kokonaistuotanto :lampopumppu]
    [:tulokset :uusiutuvat-omavaraisenergiat-kokonaistuotanto :muulampo]
    [:tulokset :uusiutuvat-omavaraisenergiat-kokonaistuotanto :muusahko]
    [:tulokset :tekniset-jarjestelmat :tilojen-lammitys :sahko]
    [:tulokset :tekniset-jarjestelmat :tilojen-lammitys :lampo]
    [:tulokset :tekniset-jarjestelmat :tuloilman-lammitys :sahko]
    [:tulokset :tekniset-jarjestelmat :tuloilman-lammitys :lampo]
    [:tulokset :tekniset-jarjestelmat :kayttoveden-valmistus :sahko]
    [:tulokset :tekniset-jarjestelmat :kayttoveden-valmistus :lampo]
    [:tulokset :tekniset-jarjestelmat :iv-sahko]
    [:tulokset :tekniset-jarjestelmat :jaahdytys :sahko]
    [:tulokset :tekniset-jarjestelmat :jaahdytys :lampo]
    [:tulokset :tekniset-jarjestelmat :jaahdytys :kaukojaahdytys]
    [:tulokset :tekniset-jarjestelmat :kuluttajalaitteet-ja-valaistus-sahko]
    [:tulokset :tekniset-jarjestelmat :sahko-summa]
    [:tulokset :tekniset-jarjestelmat :lampo-summa]
    [:tulokset :tekniset-jarjestelmat :kaukojaahdytys-summa]
    [:tulokset :nettotarve :tilojen-lammitys-vuosikulutus]
    [:tulokset :nettotarve :tilojen-lammitys-vuosikulutus-nettoala]
    [:tulokset :nettotarve :ilmanvaihdon-lammitys-vuosikulutus]
    [:tulokset :nettotarve :ilmanvaihdon-lammitys-vuosikulutus-nettoala]
    [:tulokset :nettotarve :kayttoveden-valmistus-vuosikulutus]
    [:tulokset :nettotarve :kayttoveden-valmistus-vuosikulutus-nettoala]
    [:tulokset :nettotarve :jaahdytys-vuosikulutus]
    [:tulokset :nettotarve :jaahdytys-vuosikulutus-nettoala]
    [:tulokset :lampokuormat :aurinko]
    [:tulokset :lampokuormat :aurinko-nettoala]
    [:tulokset :lampokuormat :ihmiset]
    [:tulokset :lampokuormat :ihmiset-nettoala]
    [:tulokset :lampokuormat :kuluttajalaitteet]
    [:tulokset :lampokuormat :kuluttajalaitteet-nettoala]
    [:tulokset :lampokuormat :valaistus]
    [:tulokset :lampokuormat :valaistus-nettoala]
    [:tulokset :lampokuormat :kvesi]
    [:tulokset :lampokuormat :kvesi-nettoala]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :kaukolampo-vuosikulutus]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :kaukolampo-vuosikulutus-nettoala]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :kokonaissahko-vuosikulutus]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :kokonaissahko-vuosikulutus-nettoala]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :kiinteistosahko-vuosikulutus]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :kiinteistosahko-vuosikulutus-nettoala]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :kayttajasahko-vuosikulutus]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :kayttajasahko-vuosikulutus-nettoala]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :kaukojaahdytys-vuosikulutus]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :kaukojaahdytys-vuosikulutus-nettoala]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :muu 0 :nimi-fi]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :muu 0 :nimi-sv]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :muu 0 :vuosikulutus]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :muu 0 :vuosikulutus-nettoala]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :muu 1 :nimi-fi]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :muu 1 :nimi-sv]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :muu 1 :vuosikulutus]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :muu 1 :vuosikulutus-nettoala]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :muu 2 :nimi-fi]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :muu 2 :nimi-sv]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :muu 2 :vuosikulutus]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :muu 2 :vuosikulutus-nettoala]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :muu 3 :nimi-fi]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :muu 3 :nimi-sv]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :muu 3 :vuosikulutus]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :muu 3 :vuosikulutus-nettoala]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :muu 4 :nimi-fi]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :muu 4 :nimi-sv]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :muu 4 :vuosikulutus]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :muu 4 :vuosikulutus-nettoala]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :kevyt-polttooljy]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :kevyt-polttooljy-kerroin]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :kevyt-polttooljy-kwh]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :kevyt-polttooljy-kwh-nettoala]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :pilkkeet-havu-sekapuu]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :pilkkeet-havu-sekapuu-kerroin]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :pilkkeet-havu-sekapuu-kwh]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :pilkkeet-havu-sekapuu-kwh-nettoala]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :pilkkeet-koivu]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :pilkkeet-koivu-kerroin]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :pilkkeet-koivu-kwh]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :pilkkeet-koivu-kwh-nettoala]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :puupelletit]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :puupelletit-kerroin]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :puupelletit-kwh]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :puupelletit-kwh-nettoala]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :muu 0 :nimi]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :muu 0 :maara-vuodessa]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :muu 0 :yksikko]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :muu 0 :muunnoskerroin]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :muu 0 :kwh]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :muu 0 :kwh-nettoala]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :muu 1 :nimi]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :muu 1 :maara-vuodessa]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :muu 1 :yksikko]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :muu 1 :muunnoskerroin]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :muu 1 :kwh]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :muu 1 :kwh-nettoala]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :muu 2 :nimi]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :muu 2 :maara-vuodessa]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :muu 2 :yksikko]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :muu 2 :muunnoskerroin]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :muu 2 :kwh]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :muu 2 :kwh-nettoala]
    [:toteutunut-ostoenergiankulutus :sahko-vuosikulutus-yhteensa]
    [:toteutunut-ostoenergiankulutus :sahko-vuosikulutus-yhteensa-nettoala]
    [:toteutunut-ostoenergiankulutus :kaukolampo-vuosikulutus-yhteensa]
    [:toteutunut-ostoenergiankulutus :kaukolampo-vuosikulutus-yhteensa-nettoala]
    [:toteutunut-ostoenergiankulutus :polttoaineet-vuosikulutus-yhteensa]
    [:toteutunut-ostoenergiankulutus :polttoaineet-vuosikulutus-yhteensa-nettoala]
    [:toteutunut-ostoenergiankulutus :kaukojaahdytys-vuosikulutus-yhteensa]
    [:toteutunut-ostoenergiankulutus :kaukojaahdytys-vuosikulutus-yhteensa-nettoala]
    [:toteutunut-ostoenergiankulutus :summa]
    [:toteutunut-ostoenergiankulutus :summa-nettoala]
    [:toteutunut-ostoenergiankulutus :tietojen-alkuperavuosi]
    [:toteutunut-ostoenergiankulutus :lisatietoja-fi]
    [:toteutunut-ostoenergiankulutus :lisatietoja-sv]
    [:toteutunut-ostoenergiankulutus :uusiutuvat-polttoaineet-vuosikulutus-yhteensa]
    [:toteutunut-ostoenergiankulutus :uusiutuvat-polttoaineet-vuosikulutus-yhteensa-nettoala]
    [:toteutunut-ostoenergiankulutus :fossiiliset-polttoaineet-vuosikulutus-yhteensa]
    [:toteutunut-ostoenergiankulutus :fossiiliset-polttoaineet-vuosikulutus-yhteensa-nettoala]
    [:toteutunut-ostoenergiankulutus :uusiutuva-energia-vuosituotto-yhteensa]
    [:toteutunut-ostoenergiankulutus :uusiutuva-energia-vuosituotto-yhteensa-nettoala]
    [:huomiot :ymparys :teksti-fi]
    [:huomiot :ymparys :teksti-sv]
    [:huomiot :ymparys :toimenpide 0 :nimi-fi]
    [:huomiot :ymparys :toimenpide 0 :nimi-sv]
    [:huomiot :ymparys :toimenpide 0 :lampo]
    [:huomiot :ymparys :toimenpide 0 :sahko]
    [:huomiot :ymparys :toimenpide 0 :jaahdytys]
    [:huomiot :ymparys :toimenpide 0 :eluvun-muutos]
    [:huomiot :ymparys :toimenpide 0 :kasvihuonepaastojen-muutos]
    [:huomiot :ymparys :toimenpide 1 :nimi-fi]
    [:huomiot :ymparys :toimenpide 1 :nimi-sv]
    [:huomiot :ymparys :toimenpide 1 :lampo]
    [:huomiot :ymparys :toimenpide 1 :sahko]
    [:huomiot :ymparys :toimenpide 1 :jaahdytys]
    [:huomiot :ymparys :toimenpide 1 :eluvun-muutos]
    [:huomiot :ymparys :toimenpide 1 :kasvihuonepaastojen-muutos]
    [:huomiot :ymparys :toimenpide 2 :nimi-fi]
    [:huomiot :ymparys :toimenpide 2 :nimi-sv]
    [:huomiot :ymparys :toimenpide 2 :lampo]
    [:huomiot :ymparys :toimenpide 2 :sahko]
    [:huomiot :ymparys :toimenpide 2 :jaahdytys]
    [:huomiot :ymparys :toimenpide 2 :eluvun-muutos]
    [:huomiot :ymparys :toimenpide 2 :kasvihuonepaastojen-muutos]
    [:huomiot :alapohja-ylapohja :teksti-fi]
    [:huomiot :alapohja-ylapohja :teksti-sv]
    [:huomiot :alapohja-ylapohja :toimenpide 0 :nimi-fi]
    [:huomiot :alapohja-ylapohja :toimenpide 0 :nimi-sv]
    [:huomiot :alapohja-ylapohja :toimenpide 0 :lampo]
    [:huomiot :alapohja-ylapohja :toimenpide 0 :sahko]
    [:huomiot :alapohja-ylapohja :toimenpide 0 :jaahdytys]
    [:huomiot :alapohja-ylapohja :toimenpide 0 :eluvun-muutos]
    [:huomiot :alapohja-ylapohja :toimenpide 0 :kasvihuonepaastojen-muutos]
    [:huomiot :alapohja-ylapohja :toimenpide 1 :nimi-fi]
    [:huomiot :alapohja-ylapohja :toimenpide 1 :nimi-sv]
    [:huomiot :alapohja-ylapohja :toimenpide 1 :lampo]
    [:huomiot :alapohja-ylapohja :toimenpide 1 :sahko]
    [:huomiot :alapohja-ylapohja :toimenpide 1 :jaahdytys]
    [:huomiot :alapohja-ylapohja :toimenpide 1 :eluvun-muutos]
    [:huomiot :alapohja-ylapohja :toimenpide 1 :kasvihuonepaastojen-muutos]
    [:huomiot :alapohja-ylapohja :toimenpide 2 :nimi-fi]
    [:huomiot :alapohja-ylapohja :toimenpide 2 :nimi-sv]
    [:huomiot :alapohja-ylapohja :toimenpide 2 :lampo]
    [:huomiot :alapohja-ylapohja :toimenpide 2 :sahko]
    [:huomiot :alapohja-ylapohja :toimenpide 2 :jaahdytys]
    [:huomiot :alapohja-ylapohja :toimenpide 2 :eluvun-muutos]
    [:huomiot :alapohja-ylapohja :toimenpide 2 :kasvihuonepaastojen-muutos]
    [:huomiot :lammitys :teksti-fi]
    [:huomiot :lammitys :teksti-sv]
    [:huomiot :lammitys :toimenpide 0 :nimi-fi]
    [:huomiot :lammitys :toimenpide 0 :nimi-sv]
    [:huomiot :lammitys :toimenpide 0 :lampo]
    [:huomiot :lammitys :toimenpide 0 :sahko]
    [:huomiot :lammitys :toimenpide 0 :jaahdytys]
    [:huomiot :lammitys :toimenpide 0 :eluvun-muutos]
    [:huomiot :lammitys :toimenpide 0 :kasvihuonepaastojen-muutos]
    [:huomiot :lammitys :toimenpide 1 :nimi-fi]
    [:huomiot :lammitys :toimenpide 1 :nimi-sv]
    [:huomiot :lammitys :toimenpide 1 :lampo]
    [:huomiot :lammitys :toimenpide 1 :sahko]
    [:huomiot :lammitys :toimenpide 1 :jaahdytys]
    [:huomiot :lammitys :toimenpide 1 :eluvun-muutos]
    [:huomiot :lammitys :toimenpide 1 :kasvihuonepaastojen-muutos]
    [:huomiot :lammitys :toimenpide 2 :nimi-fi]
    [:huomiot :lammitys :toimenpide 2 :nimi-sv]
    [:huomiot :lammitys :toimenpide 2 :lampo]
    [:huomiot :lammitys :toimenpide 2 :sahko]
    [:huomiot :lammitys :toimenpide 2 :jaahdytys]
    [:huomiot :lammitys :toimenpide 2 :eluvun-muutos]
    [:huomiot :lammitys :toimenpide 2 :kasvihuonepaastojen-muutos]
    [:huomiot :iv-ilmastointi :teksti-fi]
    [:huomiot :iv-ilmastointi :teksti-sv]
    [:huomiot :iv-ilmastointi :toimenpide 0 :nimi-fi]
    [:huomiot :iv-ilmastointi :toimenpide 0 :nimi-sv]
    [:huomiot :iv-ilmastointi :toimenpide 0 :lampo]
    [:huomiot :iv-ilmastointi :toimenpide 0 :sahko]
    [:huomiot :iv-ilmastointi :toimenpide 0 :jaahdytys]
    [:huomiot :iv-ilmastointi :toimenpide 0 :eluvun-muutos]
    [:huomiot :iv-ilmastointi :toimenpide 0 :kasvihuonepaastojen-muutos]
    [:huomiot :iv-ilmastointi :toimenpide 1 :nimi-fi]
    [:huomiot :iv-ilmastointi :toimenpide 1 :nimi-sv]
    [:huomiot :iv-ilmastointi :toimenpide 1 :lampo]
    [:huomiot :iv-ilmastointi :toimenpide 1 :sahko]
    [:huomiot :iv-ilmastointi :toimenpide 1 :jaahdytys]
    [:huomiot :iv-ilmastointi :toimenpide 1 :eluvun-muutos]
    [:huomiot :iv-ilmastointi :toimenpide 1 :kasvihuonepaastojen-muutos]
    [:huomiot :iv-ilmastointi :toimenpide 2 :nimi-fi]
    [:huomiot :iv-ilmastointi :toimenpide 2 :nimi-sv]
    [:huomiot :iv-ilmastointi :toimenpide 2 :lampo]
    [:huomiot :iv-ilmastointi :toimenpide 2 :sahko]
    [:huomiot :iv-ilmastointi :toimenpide 2 :jaahdytys]
    [:huomiot :iv-ilmastointi :toimenpide 2 :eluvun-muutos]
    [:huomiot :iv-ilmastointi :toimenpide 2 :kasvihuonepaastojen-muutos]
    [:huomiot :valaistus-muut :teksti-fi]
    [:huomiot :valaistus-muut :teksti-sv]
    [:huomiot :valaistus-muut :toimenpide 0 :nimi-fi]
    [:huomiot :valaistus-muut :toimenpide 0 :nimi-sv]
    [:huomiot :valaistus-muut :toimenpide 0 :lampo]
    [:huomiot :valaistus-muut :toimenpide 0 :sahko]
    [:huomiot :valaistus-muut :toimenpide 0 :jaahdytys]
    [:huomiot :valaistus-muut :toimenpide 0 :eluvun-muutos]
    [:huomiot :valaistus-muut :toimenpide 0 :kasvihuonepaastojen-muutos]
    [:huomiot :valaistus-muut :toimenpide 1 :nimi-fi]
    [:huomiot :valaistus-muut :toimenpide 1 :nimi-sv]
    [:huomiot :valaistus-muut :toimenpide 1 :lampo]
    [:huomiot :valaistus-muut :toimenpide 1 :sahko]
    [:huomiot :valaistus-muut :toimenpide 1 :jaahdytys]
    [:huomiot :valaistus-muut :toimenpide 1 :eluvun-muutos]
    [:huomiot :valaistus-muut :toimenpide 1 :kasvihuonepaastojen-muutos]
    [:huomiot :valaistus-muut :toimenpide 2 :nimi-fi]
    [:huomiot :valaistus-muut :toimenpide 2 :nimi-sv]
    [:huomiot :valaistus-muut :toimenpide 2 :lampo]
    [:huomiot :valaistus-muut :toimenpide 2 :sahko]
    [:huomiot :valaistus-muut :toimenpide 2 :jaahdytys]
    [:huomiot :valaistus-muut :toimenpide 2 :eluvun-muutos]
    [:huomiot :valaistus-muut :toimenpide 2 :kasvihuonepaastojen-muutos]
    [:huomiot :lammitys :kayttoikaa-jaljella-arvio-vuosina]
    [:huomiot :suositukset-fi]
    [:huomiot :suositukset-sv]
    [:huomiot :lisatietoja-fi]
    [:huomiot :lisatietoja-sv]
    [:lisamerkintoja-fi]
    [:lisamerkintoja-sv]
    [:ilmastoselvitys :laatimisajankohta]
    [:ilmastoselvitys :laatija]
    [:ilmastoselvitys :yritys]
    [:ilmastoselvitys :yritys-osoite]
    [:ilmastoselvitys :yritys-postinumero]
    [:ilmastoselvitys :yritys-postitoimipaikka]
    [:ilmastoselvitys :laadintaperuste]
    [:ilmastoselvitys :hiilijalanjalki :rakennus :rakennustuotteiden-valmistus]
    [:ilmastoselvitys :hiilijalanjalki :rakennus :kuljetukset-tyomaavaihe]
    [:ilmastoselvitys :hiilijalanjalki :rakennus :rakennustuotteiden-vaihdot]
    [:ilmastoselvitys :hiilijalanjalki :rakennus :energiankaytto]
    [:ilmastoselvitys :hiilijalanjalki :rakennus :purkuvaihe]
    [:ilmastoselvitys :hiilijalanjalki :rakennuspaikka :rakennustuotteiden-valmistus]
    [:ilmastoselvitys :hiilijalanjalki :rakennuspaikka :kuljetukset-tyomaavaihe]
    [:ilmastoselvitys :hiilijalanjalki :rakennuspaikka :rakennustuotteiden-vaihdot]
    [:ilmastoselvitys :hiilijalanjalki :rakennuspaikka :energiankaytto]
    [:ilmastoselvitys :hiilijalanjalki :rakennuspaikka :purkuvaihe]
    [:ilmastoselvitys :hiilikadenjalki :rakennus :uudelleenkaytto]
    [:ilmastoselvitys :hiilikadenjalki :rakennus :kierratys]
    [:ilmastoselvitys :hiilikadenjalki :rakennus :ylimaarainen-uusiutuvaenergia]
    [:ilmastoselvitys :hiilikadenjalki :rakennus :hiilivarastovaikutus]
    [:ilmastoselvitys :hiilikadenjalki :rakennus :karbonatisoituminen]
    [:ilmastoselvitys :hiilikadenjalki :rakennuspaikka :uudelleenkaytto]
    [:ilmastoselvitys :hiilikadenjalki :rakennuspaikka :kierratys]
    [:ilmastoselvitys :hiilikadenjalki :rakennuspaikka :ylimaarainen-uusiutuvaenergia]
    [:ilmastoselvitys :hiilikadenjalki :rakennuspaikka :hiilivarastovaikutus]
    [:ilmastoselvitys :hiilikadenjalki :rakennuspaikka :karbonatisoituminen]))

(def ^:private expected-public-columns
  '([:id]
    [:versio]
    [:allekirjoitusaika]
    [:voimassaolo-paattymisaika]
    [:perustiedot :kieli]
    [:perustiedot :laatimisvaihe]
    [:perustiedot :havainnointikaynti]
    [:perustiedot :nimi-fi]
    [:perustiedot :nimi-sv]
    [:perustiedot :valmistumisvuosi]
    [:perustiedot :katuosoite-fi]
    [:perustiedot :katuosoite-sv]
    [:perustiedot :postinumero]
    [:perustiedot :rakennustunnus]
    [:perustiedot :kayttotarkoitus]
    [:perustiedot :alakayttotarkoitus-fi]
    [:tulokset :e-luku]
    [:tulokset :e-luokka]
    [:tulokset :e-luokka-rajat :raja-uusi-2018]
    [:tulokset :e-luokka-rajat :kayttotarkoitus :label-fi]
    [:perustiedot :keskeiset-suositukset-fi]
    [:perustiedot :keskeiset-suositukset-sv]
    [:lahtotiedot :lammitetty-nettoala]
    [:lahtotiedot :ilmanvaihto :tyyppi-id]
    [:lahtotiedot :ilmanvaihto :kuvaus-fi]
    [:lahtotiedot :ilmanvaihto :kuvaus-sv]
    [:lahtotiedot :lammitys :lammitysmuoto-1 :id]
    [:lahtotiedot :lammitys :lammitysmuoto-2 :id]
    [:lahtotiedot :lammitys :lammitysmuoto-1 :kuvaus-fi]
    [:lahtotiedot :lammitys :lammitysmuoto-1 :kuvaus-sv]
    [:lahtotiedot :lammitys :lammitysmuoto-2 :kuvaus-fi]
    [:lahtotiedot :lammitys :lammitysmuoto-2 :kuvaus-sv]
    [:lahtotiedot :lammitys :lammonjako :id]
    [:lahtotiedot :lammitys :lammonjako :kuvaus-fi]
    [:lahtotiedot :lammitys :lammonjako :kuvaus-sv]
    [:tulokset :kaytettavat-energiamuodot :kaukolampo]
    [:tulokset :kaytettavat-energiamuodot :kaukolampo-kerroin]
    [:tulokset :kaytettavat-energiamuodot :sahko]
    [:tulokset :kaytettavat-energiamuodot :sahko-kerroin]
    [:tulokset :kaytettavat-energiamuodot :uusiutuva-polttoaine]
    [:tulokset :kaytettavat-energiamuodot :uusiutuva-polttoaine-kerroin]
    [:tulokset :kaytettavat-energiamuodot :fossiilinen-polttoaine]
    [:tulokset :kaytettavat-energiamuodot :fossiilinen-polttoaine-kerroin]
    [:tulokset :kaytettavat-energiamuodot :kaukojaahdytys]
    [:tulokset :kaytettavat-energiamuodot :kaukojaahdytys-kerroin]
    [:tulokset :kaytettavat-energiamuodot :muu 0 :nimi]
    [:tulokset :kaytettavat-energiamuodot :muu 0 :ostoenergia]
    [:tulokset :kaytettavat-energiamuodot :muu 0 :muotokerroin]
    [:tulokset :kaytettavat-energiamuodot :muu 1 :nimi]
    [:tulokset :kaytettavat-energiamuodot :muu 1 :ostoenergia]
    [:tulokset :kaytettavat-energiamuodot :muu 1 :muotokerroin]
    [:tulokset :kaytettavat-energiamuodot :muu 2 :nimi]
    [:tulokset :kaytettavat-energiamuodot :muu 2 :ostoenergia]
    [:tulokset :kaytettavat-energiamuodot :muu 2 :muotokerroin]))

(def ^:private expected-bank-columns
  '([:id]
    [:versio]
    [:allekirjoitusaika]
    [:voimassaolo-paattymisaika]
    [:perustiedot :kieli]
    [:perustiedot :kieli-fi]
    [:perustiedot :laatimisvaihe]
    [:perustiedot :laatimisvaihe-fi]
    [:perustiedot :havainnointikaynti]
    [:perustiedot :nimi-fi]
    [:perustiedot :nimi-sv]
    [:perustiedot :valmistumisvuosi]
    [:perustiedot :katuosoite-fi]
    [:perustiedot :katuosoite-sv]
    [:perustiedot :postinumero]
    [:perustiedot :postitoimipaikka-fi]
    [:perustiedot :postitoimipaikka-sv]
    [:perustiedot :rakennustunnus]
    [:perustiedot :kiinteistotunnus]
    [:perustiedot :paakayttotarkoitus-id]
    [:perustiedot :paakayttotarkoitus-fi]
    [:perustiedot :kayttotarkoitus]
    [:perustiedot :alakayttotarkoitus-fi]
    [:tulokset :e-luku]
    [:tulokset :e-luokka]
    [:tulokset :e-luokka-rajat :raja-uusi-2018]
    [:tulokset :e-luokka-rajat :kayttotarkoitus :label-fi]
    [:perustiedot :keskeiset-suositukset-fi]
    [:perustiedot :keskeiset-suositukset-sv]
    [:lahtotiedot :lammitetty-nettoala]
    [:lahtotiedot :ilmanvaihto :tyyppi-id]
    [:lahtotiedot :ilmanvaihto :label-fi]
    [:lahtotiedot :ilmanvaihto :kuvaus-fi]
    [:lahtotiedot :ilmanvaihto :kuvaus-sv]
    [:lahtotiedot :lammitys :lammitysmuoto-1 :id]
    [:lahtotiedot :lammitys :lammitysmuoto-2 :id]
    [:lahtotiedot :lammitys :lammitysmuoto-label-fi]
    [:lahtotiedot :lammitys :lammitysmuoto-1 :kuvaus-fi]
    [:lahtotiedot :lammitys :lammitysmuoto-1 :kuvaus-sv]
    [:lahtotiedot :lammitys :lammitysmuoto-2 :kuvaus-fi]
    [:lahtotiedot :lammitys :lammitysmuoto-2 :kuvaus-sv]
    [:lahtotiedot :lammitys :lammonjako :id]
    [:lahtotiedot :lammitys :lammonjako-label-fi]
    [:lahtotiedot :lammitys :lammonjako :kuvaus-fi]
    [:lahtotiedot :lammitys :lammonjako :kuvaus-sv]
    [:tulokset :kaytettavat-energiamuodot :kaukolampo]
    [:tulokset :kaytettavat-energiamuodot :kaukolampo-kerroin]
    [:tulokset :kaytettavat-energiamuodot :sahko]
    [:tulokset :kaytettavat-energiamuodot :sahko-kerroin]
    [:tulokset :kaytettavat-energiamuodot :uusiutuva-polttoaine]
    [:tulokset :kaytettavat-energiamuodot :uusiutuva-polttoaine-kerroin]
    [:tulokset :kaytettavat-energiamuodot :fossiilinen-polttoaine]
    [:tulokset :kaytettavat-energiamuodot :fossiilinen-polttoaine-kerroin]
    [:tulokset :kaytettavat-energiamuodot :kaukojaahdytys]
    [:tulokset :kaytettavat-energiamuodot :kaukojaahdytys-kerroin]
    [:tulokset :kaytettavat-energiamuodot :muu 0 :nimi]
    [:tulokset :kaytettavat-energiamuodot :muu 0 :ostoenergia]
    [:tulokset :kaytettavat-energiamuodot :muu 0 :muotokerroin]
    [:tulokset :kaytettavat-energiamuodot :muu 1 :nimi]
    [:tulokset :kaytettavat-energiamuodot :muu 1 :ostoenergia]
    [:tulokset :kaytettavat-energiamuodot :muu 1 :muotokerroin]
    [:tulokset :kaytettavat-energiamuodot :muu 2 :nimi]
    [:tulokset :kaytettavat-energiamuodot :muu 2 :ostoenergia]
    [:tulokset :kaytettavat-energiamuodot :muu 2 :muotokerroin]
    [:perustiedot :havainnointikayntityyppi-fi]
    [:perustiedot :tayttaa-aplus-vaatimukset]
    [:perustiedot :tayttaa-a0-vaatimukset]
    [:lahtotiedot :energiankulutuksen-valmius-reagoida-ulkoisiin-signaaleihin]
    [:lahtotiedot :lammitys :lammonjako-lampotilajousto]
    [:tulokset :kasvihuonepaastot]
    [:tulokset :kasvihuonepaastot-nettoala]
    [:tulokset :uusiutuvat-omavaraisenergiat-kokonaistuotanto :aurinkosahko]
    [:tulokset :uusiutuvat-omavaraisenergiat-kokonaistuotanto :aurinkolampo]
    [:tulokset :uusiutuvat-omavaraisenergiat-kokonaistuotanto :tuulisahko]
    [:tulokset :uusiutuvat-omavaraisenergiat-kokonaistuotanto :lampopumppu]
    [:tulokset :uusiutuvat-omavaraisenergiat-kokonaistuotanto :muulampo]
    [:tulokset :uusiutuvat-omavaraisenergiat-kokonaistuotanto :muusahko]
    [:ilmastoselvitys :hiilijalanjalki :rakennus :yhteensa]))

(def ^:private expected-anonymized-columns
  '([:versio]
    [:tila-id]
    [:allekirjoitusaika]
    [:voimassaolo-paattymisaika]
    [:perustiedot :kieli]
    [:perustiedot :laatimisvaihe]
    [:perustiedot :havainnointikaynti]
    [:perustiedot :uudisrakennus]
    [:perustiedot :valmistumisvuosi]
    [:perustiedot :postinumero]
    [:perustiedot :postitoimipaikka-fi]
    [:perustiedot :paakayttotarkoitus-fi]
    [:perustiedot :kayttotarkoitus]
    [:perustiedot :alakayttotarkoitus-fi]
    [:perustiedot :julkinen-rakennus]
    [:tulokset :e-luku]
    [:tulokset :e-luokka]
    [:tulokset :e-luokka-rajat :raja-uusi-2018]
    [:tulokset :e-luokka-rajat :kayttotarkoitus :label-fi]
    [:perustiedot :keskeiset-suositukset-fi]
    [:perustiedot :keskeiset-suositukset-sv]
    [:lahtotiedot :lammitetty-nettoala]
    [:lahtotiedot :rakennusvaippa :ilmanvuotoluku]
    [:lahtotiedot :rakennusvaippa :lampokapasiteetti]
    [:lahtotiedot :rakennusvaippa :ilmatilavuus]
    [:lahtotiedot :rakennusvaippa :ulkoseinat :ala]
    [:lahtotiedot :rakennusvaippa :ulkoseinat :U]
    [:lahtotiedot :rakennusvaippa :ylapohja :ala]
    [:lahtotiedot :rakennusvaippa :ylapohja :U]
    [:lahtotiedot :rakennusvaippa :alapohja :ala]
    [:lahtotiedot :rakennusvaippa :alapohja :U]
    [:lahtotiedot :rakennusvaippa :ikkunat :ala]
    [:lahtotiedot :rakennusvaippa :ikkunat :U]
    [:lahtotiedot :rakennusvaippa :ulkoovet :ala]
    [:lahtotiedot :rakennusvaippa :ulkoovet :U]
    [:lahtotiedot :rakennusvaippa :kylmasillat-UA]
    [:lahtotiedot :rakennusvaippa :kylmasillat-osuus-lampohaviosta]
    [:lahtotiedot :rakennusvaippa :UA-summa]
    [:lahtotiedot :ikkunat :pohjoinen :ala]
    [:lahtotiedot :ikkunat :pohjoinen :U]
    [:lahtotiedot :ikkunat :pohjoinen :g-ks]
    [:lahtotiedot :ikkunat :koillinen :ala]
    [:lahtotiedot :ikkunat :koillinen :U]
    [:lahtotiedot :ikkunat :koillinen :g-ks]
    [:lahtotiedot :ikkunat :ita :ala]
    [:lahtotiedot :ikkunat :ita :U]
    [:lahtotiedot :ikkunat :ita :g-ks]
    [:lahtotiedot :ikkunat :kaakko :ala]
    [:lahtotiedot :ikkunat :kaakko :U]
    [:lahtotiedot :ikkunat :kaakko :g-ks]
    [:lahtotiedot :ikkunat :etela :ala]
    [:lahtotiedot :ikkunat :etela :U]
    [:lahtotiedot :ikkunat :etela :g-ks]
    [:lahtotiedot :ikkunat :lounas :ala]
    [:lahtotiedot :ikkunat :lounas :U]
    [:lahtotiedot :ikkunat :lounas :g-ks]
    [:lahtotiedot :ikkunat :lansi :ala]
    [:lahtotiedot :ikkunat :lansi :U]
    [:lahtotiedot :ikkunat :lansi :g-ks]
    [:lahtotiedot :ikkunat :luode :ala]
    [:lahtotiedot :ikkunat :luode :U]
    [:lahtotiedot :ikkunat :luode :g-ks]
    [:lahtotiedot :ikkunat :valokupu :ala]
    [:lahtotiedot :ikkunat :valokupu :U]
    [:lahtotiedot :ikkunat :valokupu :g-ks]
    [:lahtotiedot :ikkunat :katto :ala]
    [:lahtotiedot :ikkunat :katto :U]
    [:lahtotiedot :ikkunat :katto :g-ks]
    [:lahtotiedot :ilmanvaihto :tyyppi-id]
    [:lahtotiedot :ilmanvaihto :label-fi]
    [:lahtotiedot :ilmanvaihto :kuvaus-fi]
    [:lahtotiedot :ilmanvaihto :kuvaus-sv]
    [:lahtotiedot :ilmanvaihto :paaiv :tulo]
    [:lahtotiedot :ilmanvaihto :paaiv :poisto]
    [:lahtotiedot :ilmanvaihto :paaiv :tulo-poisto]
    [:lahtotiedot :ilmanvaihto :paaiv :sfp]
    [:lahtotiedot :ilmanvaihto :paaiv :lampotilasuhde]
    [:lahtotiedot :ilmanvaihto :paaiv :jaatymisenesto]
    [:lahtotiedot :ilmanvaihto :erillispoistot :tulo]
    [:lahtotiedot :ilmanvaihto :erillispoistot :poisto]
    [:lahtotiedot :ilmanvaihto :erillispoistot :tulo-poisto]
    [:lahtotiedot :ilmanvaihto :erillispoistot :sfp]
    [:lahtotiedot :ilmanvaihto :ivjarjestelma :tulo]
    [:lahtotiedot :ilmanvaihto :ivjarjestelma :poisto]
    [:lahtotiedot :ilmanvaihto :ivjarjestelma :tulo-poisto]
    [:lahtotiedot :ilmanvaihto :ivjarjestelma :sfp]
    [:lahtotiedot :ilmanvaihto :lto-vuosihyotysuhde]
    [:lahtotiedot :ilmanvaihto :tuloilma-lampotila]
    [:lahtotiedot :lammitys :lammitysmuoto-1 :id]
    [:lahtotiedot :lammitys :lammitysmuoto-2 :id]
    [:lahtotiedot :lammitys :lammitysmuoto-label-fi]
    [:lahtotiedot :lammitys :lammitysmuoto-1 :kuvaus-fi]
    [:lahtotiedot :lammitys :lammitysmuoto-1 :kuvaus-sv]
    [:lahtotiedot :lammitys :lammitysmuoto-2 :kuvaus-fi]
    [:lahtotiedot :lammitys :lammitysmuoto-2 :kuvaus-sv]
    [:lahtotiedot :lammitys :lammonjako :id]
    [:lahtotiedot :lammitys :lammonjako-label-fi]
    [:lahtotiedot :lammitys :lammonjako :kuvaus-fi]
    [:lahtotiedot :lammitys :lammonjako :kuvaus-sv]
    [:lahtotiedot :lammitys :tilat-ja-iv :tuoton-hyotysuhde]
    [:lahtotiedot :lammitys :tilat-ja-iv :jaon-hyotysuhde]
    [:lahtotiedot :lammitys :tilat-ja-iv :lampokerroin]
    [:lahtotiedot :lammitys :tilat-ja-iv :apulaitteet]
    [:lahtotiedot :lammitys :tilat-ja-iv :lampopumppu-tuotto-osuus]
    [:lahtotiedot :lammitys :tilat-ja-iv :lampohavio-lammittamaton-tila]
    [:lahtotiedot :lammitys :lammin-kayttovesi :tuoton-hyotysuhde]
    [:lahtotiedot :lammitys :lammin-kayttovesi :jaon-hyotysuhde]
    [:lahtotiedot :lammitys :lammin-kayttovesi :lampokerroin]
    [:lahtotiedot :lammitys :lammin-kayttovesi :apulaitteet]
    [:lahtotiedot :lammitys :lammin-kayttovesi :lampopumppu-tuotto-osuus]
    [:lahtotiedot :lammitys :lammin-kayttovesi :lampohavio-lammittamaton-tila]
    [:lahtotiedot :lammitys :takka :maara]
    [:lahtotiedot :lammitys :takka :tuotto]
    [:lahtotiedot :lammitys :ilmalampopumppu :maara]
    [:lahtotiedot :lammitys :ilmalampopumppu :tuotto]
    [:lahtotiedot :jaahdytysjarjestelma :jaahdytyskauden-painotettu-kylmakerroin]
    [:lahtotiedot :lkvn-kaytto :ominaiskulutus]
    [:lahtotiedot :lkvn-kaytto :lammitysenergian-nettotarve]
    [:lahtotiedot :sis-kuorma :henkilot :kayttoaste]
    [:lahtotiedot :sis-kuorma :henkilot :lampokuorma]
    [:lahtotiedot :sis-kuorma :kuluttajalaitteet :kayttoaste]
    [:lahtotiedot :sis-kuorma :kuluttajalaitteet :lampokuorma]
    [:lahtotiedot :sis-kuorma :valaistus :kayttoaste]
    [:lahtotiedot :sis-kuorma :valaistus :lampokuorma]
    [:tulokset :kaytettavat-energiamuodot :kaukolampo]
    [:tulokset :kaytettavat-energiamuodot :kaukolampo-nettoala]
    [:tulokset :kaytettavat-energiamuodot :kaukolampo-kerroin]
    [:tulokset :kaytettavat-energiamuodot :kaukolampo-kertoimella]
    [:tulokset :kaytettavat-energiamuodot :kaukolampo-nettoala-kertoimella]
    [:tulokset :kaytettavat-energiamuodot :sahko]
    [:tulokset :kaytettavat-energiamuodot :sahko-nettoala]
    [:tulokset :kaytettavat-energiamuodot :sahko-kerroin]
    [:tulokset :kaytettavat-energiamuodot :sahko-kertoimella]
    [:tulokset :kaytettavat-energiamuodot :sahko-nettoala-kertoimella]
    [:tulokset :kaytettavat-energiamuodot :uusiutuva-polttoaine]
    [:tulokset :kaytettavat-energiamuodot :uusiutuva-polttoaine-nettoala]
    [:tulokset :kaytettavat-energiamuodot :uusiutuva-polttoaine-kerroin]
    [:tulokset :kaytettavat-energiamuodot :uusiutuva-polttoaine-kertoimella]
    [:tulokset :kaytettavat-energiamuodot :uusiutuva-polttoaine-nettoala-kertoimella]
    [:tulokset :kaytettavat-energiamuodot :fossiilinen-polttoaine]
    [:tulokset :kaytettavat-energiamuodot :fossiilinen-polttoaine-nettoala]
    [:tulokset :kaytettavat-energiamuodot :fossiilinen-polttoaine-kerroin]
    [:tulokset :kaytettavat-energiamuodot :fossiilinen-polttoaine-kertoimella]
    [:tulokset :kaytettavat-energiamuodot :fossiilinen-polttoaine-nettoala-kertoimella]
    [:tulokset :kaytettavat-energiamuodot :kaukojaahdytys]
    [:tulokset :kaytettavat-energiamuodot :kaukojaahdytys-nettoala]
    [:tulokset :kaytettavat-energiamuodot :kaukojaahdytys-kerroin]
    [:tulokset :kaytettavat-energiamuodot :kaukojaahdytys-kertoimella]
    [:tulokset :kaytettavat-energiamuodot :kaukojaahdytys-nettoala-kertoimella]
    [:tulokset :kaytettavat-energiamuodot :muu 0 :nimi]
    [:tulokset :kaytettavat-energiamuodot :muu 0 :ostoenergia]
    [:tulokset :kaytettavat-energiamuodot :muu 0 :muotokerroin]
    [:tulokset :kaytettavat-energiamuodot :muu 0 :ostoenergia-nettoala]
    [:tulokset :kaytettavat-energiamuodot :muu 0 :ostoenergia-kertoimella]
    [:tulokset :kaytettavat-energiamuodot :muu 0 :ostoenergia-nettoala-kertoimella]
    [:tulokset :kaytettavat-energiamuodot :muu 1 :nimi]
    [:tulokset :kaytettavat-energiamuodot :muu 1 :ostoenergia]
    [:tulokset :kaytettavat-energiamuodot :muu 1 :muotokerroin]
    [:tulokset :kaytettavat-energiamuodot :muu 1 :ostoenergia-nettoala]
    [:tulokset :kaytettavat-energiamuodot :muu 1 :ostoenergia-kertoimella]
    [:tulokset :kaytettavat-energiamuodot :muu 1 :ostoenergia-nettoala-kertoimella]
    [:tulokset :kaytettavat-energiamuodot :muu 2 :nimi]
    [:tulokset :kaytettavat-energiamuodot :muu 2 :ostoenergia]
    [:tulokset :kaytettavat-energiamuodot :muu 2 :muotokerroin]
    [:tulokset :kaytettavat-energiamuodot :muu 2 :ostoenergia-nettoala]
    [:tulokset :kaytettavat-energiamuodot :muu 2 :ostoenergia-kertoimella]
    [:tulokset :kaytettavat-energiamuodot :muu 2 :ostoenergia-nettoala-kertoimella]
    [:tulokset :kaytettavat-energiamuodot :summa]
    [:tulokset :kaytettavat-energiamuodot :kertoimella-summa]
    [:tulokset :uusiutuvat-omavaraisenergiat :aurinkosahko]
    [:tulokset :uusiutuvat-omavaraisenergiat :aurinkosahko-nettoala]
    [:tulokset :uusiutuvat-omavaraisenergiat :aurinkolampo]
    [:tulokset :uusiutuvat-omavaraisenergiat :aurinkolampo-nettoala]
    [:tulokset :uusiutuvat-omavaraisenergiat :tuulisahko]
    [:tulokset :uusiutuvat-omavaraisenergiat :tuulisahko-nettoala]
    [:tulokset :uusiutuvat-omavaraisenergiat :lampopumppu]
    [:tulokset :uusiutuvat-omavaraisenergiat :lampopumppu-nettoala]
    [:tulokset :uusiutuvat-omavaraisenergiat :muusahko]
    [:tulokset :uusiutuvat-omavaraisenergiat :muusahko-nettoala]
    [:tulokset :uusiutuvat-omavaraisenergiat :muulampo]
    [:tulokset :uusiutuvat-omavaraisenergiat :muulampo-nettoala]
    [:tulokset :uusiutuvat-omavaraisenergiat 0 :nimi-fi]
    [:tulokset :uusiutuvat-omavaraisenergiat 0 :nimi-sv]
    [:tulokset :uusiutuvat-omavaraisenergiat 0 :vuosikulutus]
    [:tulokset :uusiutuvat-omavaraisenergiat 0 :vuosikulutus-nettoala]
    [:tulokset :uusiutuvat-omavaraisenergiat 1 :nimi-fi]
    [:tulokset :uusiutuvat-omavaraisenergiat 1 :nimi-sv]
    [:tulokset :uusiutuvat-omavaraisenergiat 1 :vuosikulutus]
    [:tulokset :uusiutuvat-omavaraisenergiat 1 :vuosikulutus-nettoala]
    [:tulokset :uusiutuvat-omavaraisenergiat 2 :nimi-fi]
    [:tulokset :uusiutuvat-omavaraisenergiat 2 :nimi-sv]
    [:tulokset :uusiutuvat-omavaraisenergiat 2 :vuosikulutus]
    [:tulokset :uusiutuvat-omavaraisenergiat 2 :vuosikulutus-nettoala]
    [:tulokset :uusiutuvat-omavaraisenergiat 3 :nimi-fi]
    [:tulokset :uusiutuvat-omavaraisenergiat 3 :nimi-sv]
    [:tulokset :uusiutuvat-omavaraisenergiat 3 :vuosikulutus]
    [:tulokset :uusiutuvat-omavaraisenergiat 3 :vuosikulutus-nettoala]
    [:tulokset :uusiutuvat-omavaraisenergiat 4 :nimi-fi]
    [:tulokset :uusiutuvat-omavaraisenergiat 4 :nimi-sv]
    [:tulokset :uusiutuvat-omavaraisenergiat 4 :vuosikulutus]
    [:tulokset :uusiutuvat-omavaraisenergiat 4 :vuosikulutus-nettoala]
    [:tulokset :uusiutuvat-omavaraisenergiat 5 :nimi-fi]
    [:tulokset :uusiutuvat-omavaraisenergiat 5 :nimi-sv]
    [:tulokset :uusiutuvat-omavaraisenergiat 5 :vuosikulutus]
    [:tulokset :uusiutuvat-omavaraisenergiat 5 :vuosikulutus-nettoala]
    [:tulokset :tekniset-jarjestelmat :tilojen-lammitys :sahko]
    [:tulokset :tekniset-jarjestelmat :tilojen-lammitys :lampo]
    [:tulokset :tekniset-jarjestelmat :tuloilman-lammitys :sahko]
    [:tulokset :tekniset-jarjestelmat :tuloilman-lammitys :lampo]
    [:tulokset :tekniset-jarjestelmat :kayttoveden-valmistus :sahko]
    [:tulokset :tekniset-jarjestelmat :kayttoveden-valmistus :lampo]
    [:tulokset :tekniset-jarjestelmat :iv-sahko]
    [:tulokset :tekniset-jarjestelmat :jaahdytys :sahko]
    [:tulokset :tekniset-jarjestelmat :jaahdytys :lampo]
    [:tulokset :tekniset-jarjestelmat :jaahdytys :kaukojaahdytys]
    [:tulokset :tekniset-jarjestelmat :kuluttajalaitteet-ja-valaistus-sahko]
    [:tulokset :tekniset-jarjestelmat :sahko-summa]
    [:tulokset :tekniset-jarjestelmat :lampo-summa]
    [:tulokset :tekniset-jarjestelmat :kaukojaahdytys-summa]
    [:tulokset :nettotarve :tilojen-lammitys-vuosikulutus]
    [:tulokset :nettotarve :tilojen-lammitys-vuosikulutus-nettoala]
    [:tulokset :nettotarve :ilmanvaihdon-lammitys-vuosikulutus]
    [:tulokset :nettotarve :ilmanvaihdon-lammitys-vuosikulutus-nettoala]
    [:tulokset :nettotarve :kayttoveden-valmistus-vuosikulutus]
    [:tulokset :nettotarve :kayttoveden-valmistus-vuosikulutus-nettoala]
    [:tulokset :nettotarve :jaahdytys-vuosikulutus]
    [:tulokset :nettotarve :jaahdytys-vuosikulutus-nettoala]
    [:tulokset :lampokuormat :aurinko]
    [:tulokset :lampokuormat :aurinko-nettoala]
    [:tulokset :lampokuormat :ihmiset]
    [:tulokset :lampokuormat :ihmiset-nettoala]
    [:tulokset :lampokuormat :kuluttajalaitteet]
    [:tulokset :lampokuormat :kuluttajalaitteet-nettoala]
    [:tulokset :lampokuormat :valaistus]
    [:tulokset :lampokuormat :valaistus-nettoala]
    [:tulokset :lampokuormat :kvesi]
    [:tulokset :lampokuormat :kvesi-nettoala]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :kaukolampo-vuosikulutus]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :kaukolampo-vuosikulutus-nettoala]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :kokonaissahko-vuosikulutus]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :kokonaissahko-vuosikulutus-nettoala]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :kiinteistosahko-vuosikulutus]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :kiinteistosahko-vuosikulutus-nettoala]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :kayttajasahko-vuosikulutus]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :kayttajasahko-vuosikulutus-nettoala]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :kaukojaahdytys-vuosikulutus]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :kaukojaahdytys-vuosikulutus-nettoala]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :muu 0 :nimi-fi]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :muu 0 :nimi-sv]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :muu 0 :vuosikulutus]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :muu 0 :vuosikulutus-nettoala]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :muu 1 :nimi-fi]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :muu 1 :nimi-sv]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :muu 1 :vuosikulutus]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :muu 1 :vuosikulutus-nettoala]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :muu 2 :nimi-fi]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :muu 2 :nimi-sv]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :muu 2 :vuosikulutus]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :muu 2 :vuosikulutus-nettoala]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :muu 3 :nimi-fi]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :muu 3 :nimi-sv]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :muu 3 :vuosikulutus]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :muu 3 :vuosikulutus-nettoala]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :muu 4 :nimi-fi]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :muu 4 :nimi-sv]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :muu 4 :vuosikulutus]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :muu 4 :vuosikulutus-nettoala]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :kevyt-polttooljy]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :kevyt-polttooljy-kerroin]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :kevyt-polttooljy-kwh]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :kevyt-polttooljy-kwh-nettoala]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :pilkkeet-havu-sekapuu]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :pilkkeet-havu-sekapuu-kerroin]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :pilkkeet-havu-sekapuu-kwh]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :pilkkeet-havu-sekapuu-kwh-nettoala]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :pilkkeet-koivu]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :pilkkeet-koivu-kerroin]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :pilkkeet-koivu-kwh]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :pilkkeet-koivu-kwh-nettoala]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :puupelletit]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :puupelletit-kerroin]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :puupelletit-kwh]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :puupelletit-kwh-nettoala]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :muu 0 :nimi]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :muu 0 :maara-vuodessa]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :muu 0 :yksikko]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :muu 0 :muunnoskerroin]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :muu 0 :kwh]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :muu 0 :kwh-nettoala]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :muu 1 :nimi]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :muu 1 :maara-vuodessa]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :muu 1 :yksikko]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :muu 1 :muunnoskerroin]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :muu 1 :kwh]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :muu 1 :kwh-nettoala]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :muu 2 :nimi]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :muu 2 :maara-vuodessa]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :muu 2 :yksikko]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :muu 2 :muunnoskerroin]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :muu 2 :kwh]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :muu 2 :kwh-nettoala]
    [:toteutunut-ostoenergiankulutus :sahko-vuosikulutus-yhteensa]
    [:toteutunut-ostoenergiankulutus :sahko-vuosikulutus-yhteensa-nettoala]
    [:toteutunut-ostoenergiankulutus :kaukolampo-vuosikulutus-yhteensa]
    [:toteutunut-ostoenergiankulutus :kaukolampo-vuosikulutus-yhteensa-nettoala]
    [:toteutunut-ostoenergiankulutus :polttoaineet-vuosikulutus-yhteensa]
    [:toteutunut-ostoenergiankulutus :polttoaineet-vuosikulutus-yhteensa-nettoala]
    [:toteutunut-ostoenergiankulutus :kaukojaahdytys-vuosikulutus-yhteensa]
    [:toteutunut-ostoenergiankulutus :kaukojaahdytys-vuosikulutus-yhteensa-nettoala]
    [:toteutunut-ostoenergiankulutus :summa]
    [:toteutunut-ostoenergiankulutus :summa-nettoala]
    [:huomiot :ymparys :teksti-fi]
    [:huomiot :ymparys :teksti-sv]
    [:huomiot :ymparys :toimenpide 0 :nimi-fi]
    [:huomiot :ymparys :toimenpide 0 :nimi-sv]
    [:huomiot :ymparys :toimenpide 0 :lampo]
    [:huomiot :ymparys :toimenpide 0 :sahko]
    [:huomiot :ymparys :toimenpide 0 :jaahdytys]
    [:huomiot :ymparys :toimenpide 0 :eluvun-muutos]
    [:huomiot :ymparys :toimenpide 1 :nimi-fi]
    [:huomiot :ymparys :toimenpide 1 :nimi-sv]
    [:huomiot :ymparys :toimenpide 1 :lampo]
    [:huomiot :ymparys :toimenpide 1 :sahko]
    [:huomiot :ymparys :toimenpide 1 :jaahdytys]
    [:huomiot :ymparys :toimenpide 1 :eluvun-muutos]
    [:huomiot :ymparys :toimenpide 2 :nimi-fi]
    [:huomiot :ymparys :toimenpide 2 :nimi-sv]
    [:huomiot :ymparys :toimenpide 2 :lampo]
    [:huomiot :ymparys :toimenpide 2 :sahko]
    [:huomiot :ymparys :toimenpide 2 :jaahdytys]
    [:huomiot :ymparys :toimenpide 2 :eluvun-muutos]
    [:huomiot :alapohja-ylapohja :teksti-fi]
    [:huomiot :alapohja-ylapohja :teksti-sv]
    [:huomiot :alapohja-ylapohja :toimenpide 0 :nimi-fi]
    [:huomiot :alapohja-ylapohja :toimenpide 0 :nimi-sv]
    [:huomiot :alapohja-ylapohja :toimenpide 0 :lampo]
    [:huomiot :alapohja-ylapohja :toimenpide 0 :sahko]
    [:huomiot :alapohja-ylapohja :toimenpide 0 :jaahdytys]
    [:huomiot :alapohja-ylapohja :toimenpide 0 :eluvun-muutos]
    [:huomiot :alapohja-ylapohja :toimenpide 1 :nimi-fi]
    [:huomiot :alapohja-ylapohja :toimenpide 1 :nimi-sv]
    [:huomiot :alapohja-ylapohja :toimenpide 1 :lampo]
    [:huomiot :alapohja-ylapohja :toimenpide 1 :sahko]
    [:huomiot :alapohja-ylapohja :toimenpide 1 :jaahdytys]
    [:huomiot :alapohja-ylapohja :toimenpide 1 :eluvun-muutos]
    [:huomiot :alapohja-ylapohja :toimenpide 2 :nimi-fi]
    [:huomiot :alapohja-ylapohja :toimenpide 2 :nimi-sv]
    [:huomiot :alapohja-ylapohja :toimenpide 2 :lampo]
    [:huomiot :alapohja-ylapohja :toimenpide 2 :sahko]
    [:huomiot :alapohja-ylapohja :toimenpide 2 :jaahdytys]
    [:huomiot :alapohja-ylapohja :toimenpide 2 :eluvun-muutos]
    [:huomiot :lammitys :teksti-fi]
    [:huomiot :lammitys :teksti-sv]
    [:huomiot :lammitys :toimenpide 0 :nimi-fi]
    [:huomiot :lammitys :toimenpide 0 :nimi-sv]
    [:huomiot :lammitys :toimenpide 0 :lampo]
    [:huomiot :lammitys :toimenpide 0 :sahko]
    [:huomiot :lammitys :toimenpide 0 :jaahdytys]
    [:huomiot :lammitys :toimenpide 0 :eluvun-muutos]
    [:huomiot :lammitys :toimenpide 1 :nimi-fi]
    [:huomiot :lammitys :toimenpide 1 :nimi-sv]
    [:huomiot :lammitys :toimenpide 1 :lampo]
    [:huomiot :lammitys :toimenpide 1 :sahko]
    [:huomiot :lammitys :toimenpide 1 :jaahdytys]
    [:huomiot :lammitys :toimenpide 1 :eluvun-muutos]
    [:huomiot :lammitys :toimenpide 2 :nimi-fi]
    [:huomiot :lammitys :toimenpide 2 :nimi-sv]
    [:huomiot :lammitys :toimenpide 2 :lampo]
    [:huomiot :lammitys :toimenpide 2 :sahko]
    [:huomiot :lammitys :toimenpide 2 :jaahdytys]
    [:huomiot :lammitys :toimenpide 2 :eluvun-muutos]
    [:huomiot :iv-ilmastointi :teksti-fi]
    [:huomiot :iv-ilmastointi :teksti-sv]
    [:huomiot :iv-ilmastointi :toimenpide 0 :nimi-fi]
    [:huomiot :iv-ilmastointi :toimenpide 0 :nimi-sv]
    [:huomiot :iv-ilmastointi :toimenpide 0 :lampo]
    [:huomiot :iv-ilmastointi :toimenpide 0 :sahko]
    [:huomiot :iv-ilmastointi :toimenpide 0 :jaahdytys]
    [:huomiot :iv-ilmastointi :toimenpide 0 :eluvun-muutos]
    [:huomiot :iv-ilmastointi :toimenpide 1 :nimi-fi]
    [:huomiot :iv-ilmastointi :toimenpide 1 :nimi-sv]
    [:huomiot :iv-ilmastointi :toimenpide 1 :lampo]
    [:huomiot :iv-ilmastointi :toimenpide 1 :sahko]
    [:huomiot :iv-ilmastointi :toimenpide 1 :jaahdytys]
    [:huomiot :iv-ilmastointi :toimenpide 1 :eluvun-muutos]
    [:huomiot :iv-ilmastointi :toimenpide 2 :nimi-fi]
    [:huomiot :iv-ilmastointi :toimenpide 2 :nimi-sv]
    [:huomiot :iv-ilmastointi :toimenpide 2 :lampo]
    [:huomiot :iv-ilmastointi :toimenpide 2 :sahko]
    [:huomiot :iv-ilmastointi :toimenpide 2 :jaahdytys]
    [:huomiot :iv-ilmastointi :toimenpide 2 :eluvun-muutos]
    [:huomiot :valaistus-muut :teksti-fi]
    [:huomiot :valaistus-muut :teksti-sv]
    [:huomiot :valaistus-muut :toimenpide 0 :nimi-fi]
    [:huomiot :valaistus-muut :toimenpide 0 :nimi-sv]
    [:huomiot :valaistus-muut :toimenpide 0 :lampo]
    [:huomiot :valaistus-muut :toimenpide 0 :sahko]
    [:huomiot :valaistus-muut :toimenpide 0 :jaahdytys]
    [:huomiot :valaistus-muut :toimenpide 0 :eluvun-muutos]
    [:huomiot :valaistus-muut :toimenpide 1 :nimi-fi]
    [:huomiot :valaistus-muut :toimenpide 1 :nimi-sv]
    [:huomiot :valaistus-muut :toimenpide 1 :lampo]
    [:huomiot :valaistus-muut :toimenpide 1 :sahko]
    [:huomiot :valaistus-muut :toimenpide 1 :jaahdytys]
    [:huomiot :valaistus-muut :toimenpide 1 :eluvun-muutos]
    [:huomiot :valaistus-muut :toimenpide 2 :nimi-fi]
    [:huomiot :valaistus-muut :toimenpide 2 :nimi-sv]
    [:huomiot :valaistus-muut :toimenpide 2 :lampo]
    [:huomiot :valaistus-muut :toimenpide 2 :sahko]
    [:huomiot :valaistus-muut :toimenpide 2 :jaahdytys]
    [:huomiot :valaistus-muut :toimenpide 2 :eluvun-muutos]
    [:huomiot :suositukset-fi]
    [:huomiot :suositukset-sv]
    [:lisamerkintoja-fi]
    [:lisamerkintoja-sv]))

(def ^:private expected-tilastokeskus-columns
  '([:id]
    [:versio]
    [:tila-id]
    [:laatija-id]
    [:allekirjoitusaika]
    [:voimassaolo-paattymisaika]
    [:korvattu-energiatodistus-id]
    [:korvaava-energiatodistus-id]
    [:perustiedot :kieli]
    [:perustiedot :laatimisvaihe]
    [:perustiedot :havainnointikaynti]
    [:perustiedot :uudisrakennus]
    [:tulokset :laskentatyokalu]
    [:perustiedot :nimi-fi]
    [:perustiedot :nimi-sv]
    [:perustiedot :valmistumisvuosi]
    [:perustiedot :rakennusosa]
    [:perustiedot :katuosoite-fi]
    [:perustiedot :katuosoite-sv]
    [:perustiedot :postinumero]
    [:perustiedot :postitoimipaikka-fi]
    [:perustiedot :rakennustunnus]
    [:perustiedot :kiinteistotunnus]
    [:perustiedot :paakayttotarkoitus-fi]
    [:perustiedot :kayttotarkoitus]
    [:perustiedot :alakayttotarkoitus-fi]
    [:perustiedot :julkinen-rakennus]
    [:tulokset :e-luku]
    [:tulokset :e-luokka]
    [:tulokset :e-luokka-rajat :raja-uusi-2018]
    [:tulokset :e-luokka-rajat :kayttotarkoitus :label-fi]
    [:perustiedot :keskeiset-suositukset-fi]
    [:perustiedot :keskeiset-suositukset-sv]
    [:lahtotiedot :lammitetty-nettoala]
    [:lahtotiedot :rakennusvaippa :ilmanvuotoluku]
    [:lahtotiedot :rakennusvaippa :lampokapasiteetti]
    [:lahtotiedot :rakennusvaippa :ilmatilavuus]
    [:lahtotiedot :rakennusvaippa :ulkoseinat :ala]
    [:lahtotiedot :rakennusvaippa :ulkoseinat :U]
    [:lahtotiedot :rakennusvaippa :ylapohja :ala]
    [:lahtotiedot :rakennusvaippa :ylapohja :U]
    [:lahtotiedot :rakennusvaippa :alapohja :ala]
    [:lahtotiedot :rakennusvaippa :alapohja :U]
    [:lahtotiedot :rakennusvaippa :ikkunat :ala]
    [:lahtotiedot :rakennusvaippa :ikkunat :U]
    [:lahtotiedot :rakennusvaippa :ulkoovet :ala]
    [:lahtotiedot :rakennusvaippa :ulkoovet :U]
    [:lahtotiedot :rakennusvaippa :kylmasillat-UA]
    [:lahtotiedot :rakennusvaippa :kylmasillat-osuus-lampohaviosta]
    [:lahtotiedot :rakennusvaippa :UA-summa]
    [:lahtotiedot :ikkunat :pohjoinen :ala]
    [:lahtotiedot :ikkunat :pohjoinen :U]
    [:lahtotiedot :ikkunat :pohjoinen :g-ks]
    [:lahtotiedot :ikkunat :koillinen :ala]
    [:lahtotiedot :ikkunat :koillinen :U]
    [:lahtotiedot :ikkunat :koillinen :g-ks]
    [:lahtotiedot :ikkunat :ita :ala]
    [:lahtotiedot :ikkunat :ita :U]
    [:lahtotiedot :ikkunat :ita :g-ks]
    [:lahtotiedot :ikkunat :kaakko :ala]
    [:lahtotiedot :ikkunat :kaakko :U]
    [:lahtotiedot :ikkunat :kaakko :g-ks]
    [:lahtotiedot :ikkunat :etela :ala]
    [:lahtotiedot :ikkunat :etela :U]
    [:lahtotiedot :ikkunat :etela :g-ks]
    [:lahtotiedot :ikkunat :lounas :ala]
    [:lahtotiedot :ikkunat :lounas :U]
    [:lahtotiedot :ikkunat :lounas :g-ks]
    [:lahtotiedot :ikkunat :lansi :ala]
    [:lahtotiedot :ikkunat :lansi :U]
    [:lahtotiedot :ikkunat :lansi :g-ks]
    [:lahtotiedot :ikkunat :luode :ala]
    [:lahtotiedot :ikkunat :luode :U]
    [:lahtotiedot :ikkunat :luode :g-ks]
    [:lahtotiedot :ikkunat :valokupu :ala]
    [:lahtotiedot :ikkunat :valokupu :U]
    [:lahtotiedot :ikkunat :valokupu :g-ks]
    [:lahtotiedot :ikkunat :katto :ala]
    [:lahtotiedot :ikkunat :katto :U]
    [:lahtotiedot :ikkunat :katto :g-ks]
    [:lahtotiedot :ilmanvaihto :tyyppi-id]
    [:lahtotiedot :ilmanvaihto :label-fi]
    [:lahtotiedot :ilmanvaihto :kuvaus-fi]
    [:lahtotiedot :ilmanvaihto :kuvaus-sv]
    [:lahtotiedot :ilmanvaihto :paaiv :tulo]
    [:lahtotiedot :ilmanvaihto :paaiv :poisto]
    [:lahtotiedot :ilmanvaihto :paaiv :tulo-poisto]
    [:lahtotiedot :ilmanvaihto :paaiv :sfp]
    [:lahtotiedot :ilmanvaihto :paaiv :lampotilasuhde]
    [:lahtotiedot :ilmanvaihto :paaiv :jaatymisenesto]
    [:lahtotiedot :ilmanvaihto :erillispoistot :tulo]
    [:lahtotiedot :ilmanvaihto :erillispoistot :poisto]
    [:lahtotiedot :ilmanvaihto :erillispoistot :tulo-poisto]
    [:lahtotiedot :ilmanvaihto :erillispoistot :sfp]
    [:lahtotiedot :ilmanvaihto :ivjarjestelma :tulo]
    [:lahtotiedot :ilmanvaihto :ivjarjestelma :poisto]
    [:lahtotiedot :ilmanvaihto :ivjarjestelma :tulo-poisto]
    [:lahtotiedot :ilmanvaihto :ivjarjestelma :sfp]
    [:lahtotiedot :ilmanvaihto :lto-vuosihyotysuhde]
    [:lahtotiedot :ilmanvaihto :tuloilma-lampotila]
    [:lahtotiedot :lammitys :lammitysmuoto-1 :id]
    [:lahtotiedot :lammitys :lammitysmuoto-2 :id]
    [:lahtotiedot :lammitys :lammitysmuoto-label-fi]
    [:lahtotiedot :lammitys :lammitysmuoto-1 :kuvaus-fi]
    [:lahtotiedot :lammitys :lammitysmuoto-1 :kuvaus-sv]
    [:lahtotiedot :lammitys :lammitysmuoto-2 :kuvaus-fi]
    [:lahtotiedot :lammitys :lammitysmuoto-2 :kuvaus-sv]
    [:lahtotiedot :lammitys :lammonjako :id]
    [:lahtotiedot :lammitys :lammonjako-label-fi]
    [:lahtotiedot :lammitys :lammonjako :kuvaus-fi]
    [:lahtotiedot :lammitys :lammonjako :kuvaus-sv]
    [:lahtotiedot :lammitys :tilat-ja-iv :tuoton-hyotysuhde]
    [:lahtotiedot :lammitys :tilat-ja-iv :jaon-hyotysuhde]
    [:lahtotiedot :lammitys :tilat-ja-iv :lampokerroin]
    [:lahtotiedot :lammitys :tilat-ja-iv :apulaitteet]
    [:lahtotiedot :lammitys :tilat-ja-iv :lampopumppu-tuotto-osuus]
    [:lahtotiedot :lammitys :tilat-ja-iv :lampohavio-lammittamaton-tila]
    [:lahtotiedot :lammitys :lammin-kayttovesi :tuoton-hyotysuhde]
    [:lahtotiedot :lammitys :lammin-kayttovesi :jaon-hyotysuhde]
    [:lahtotiedot :lammitys :lammin-kayttovesi :lampokerroin]
    [:lahtotiedot :lammitys :lammin-kayttovesi :apulaitteet]
    [:lahtotiedot :lammitys :lammin-kayttovesi :lampopumppu-tuotto-osuus]
    [:lahtotiedot :lammitys :lammin-kayttovesi :lampohavio-lammittamaton-tila]
    [:lahtotiedot :lammitys :takka :maara]
    [:lahtotiedot :lammitys :takka :tuotto]
    [:lahtotiedot :lammitys :ilmalampopumppu :maara]
    [:lahtotiedot :lammitys :ilmalampopumppu :tuotto]
    [:lahtotiedot :jaahdytysjarjestelma :jaahdytyskauden-painotettu-kylmakerroin]
    [:lahtotiedot :lkvn-kaytto :ominaiskulutus]
    [:lahtotiedot :lkvn-kaytto :lammitysenergian-nettotarve]
    [:lahtotiedot :sis-kuorma :henkilot :kayttoaste]
    [:lahtotiedot :sis-kuorma :henkilot :lampokuorma]
    [:lahtotiedot :sis-kuorma :kuluttajalaitteet :kayttoaste]
    [:lahtotiedot :sis-kuorma :kuluttajalaitteet :lampokuorma]
    [:lahtotiedot :sis-kuorma :valaistus :kayttoaste]
    [:lahtotiedot :sis-kuorma :valaistus :lampokuorma]
    [:tulokset :kaytettavat-energiamuodot :kaukolampo]
    [:tulokset :kaytettavat-energiamuodot :kaukolampo-nettoala]
    [:tulokset :kaytettavat-energiamuodot :kaukolampo-kerroin]
    [:tulokset :kaytettavat-energiamuodot :kaukolampo-kertoimella]
    [:tulokset :kaytettavat-energiamuodot :kaukolampo-nettoala-kertoimella]
    [:tulokset :kaytettavat-energiamuodot :sahko]
    [:tulokset :kaytettavat-energiamuodot :sahko-nettoala]
    [:tulokset :kaytettavat-energiamuodot :sahko-kerroin]
    [:tulokset :kaytettavat-energiamuodot :sahko-kertoimella]
    [:tulokset :kaytettavat-energiamuodot :sahko-nettoala-kertoimella]
    [:tulokset :kaytettavat-energiamuodot :uusiutuva-polttoaine]
    [:tulokset :kaytettavat-energiamuodot :uusiutuva-polttoaine-nettoala]
    [:tulokset :kaytettavat-energiamuodot :uusiutuva-polttoaine-kerroin]
    [:tulokset :kaytettavat-energiamuodot :uusiutuva-polttoaine-kertoimella]
    [:tulokset :kaytettavat-energiamuodot :uusiutuva-polttoaine-nettoala-kertoimella]
    [:tulokset :kaytettavat-energiamuodot :fossiilinen-polttoaine]
    [:tulokset :kaytettavat-energiamuodot :fossiilinen-polttoaine-nettoala]
    [:tulokset :kaytettavat-energiamuodot :fossiilinen-polttoaine-kerroin]
    [:tulokset :kaytettavat-energiamuodot :fossiilinen-polttoaine-kertoimella]
    [:tulokset :kaytettavat-energiamuodot :fossiilinen-polttoaine-nettoala-kertoimella]
    [:tulokset :kaytettavat-energiamuodot :kaukojaahdytys]
    [:tulokset :kaytettavat-energiamuodot :kaukojaahdytys-nettoala]
    [:tulokset :kaytettavat-energiamuodot :kaukojaahdytys-kerroin]
    [:tulokset :kaytettavat-energiamuodot :kaukojaahdytys-kertoimella]
    [:tulokset :kaytettavat-energiamuodot :kaukojaahdytys-nettoala-kertoimella]
    [:tulokset :kaytettavat-energiamuodot :muu 0 :nimi]
    [:tulokset :kaytettavat-energiamuodot :muu 0 :ostoenergia]
    [:tulokset :kaytettavat-energiamuodot :muu 0 :muotokerroin]
    [:tulokset :kaytettavat-energiamuodot :muu 0 :ostoenergia-nettoala]
    [:tulokset :kaytettavat-energiamuodot :muu 0 :ostoenergia-kertoimella]
    [:tulokset :kaytettavat-energiamuodot :muu 0 :ostoenergia-nettoala-kertoimella]
    [:tulokset :kaytettavat-energiamuodot :muu 1 :nimi]
    [:tulokset :kaytettavat-energiamuodot :muu 1 :ostoenergia]
    [:tulokset :kaytettavat-energiamuodot :muu 1 :muotokerroin]
    [:tulokset :kaytettavat-energiamuodot :muu 1 :ostoenergia-nettoala]
    [:tulokset :kaytettavat-energiamuodot :muu 1 :ostoenergia-kertoimella]
    [:tulokset :kaytettavat-energiamuodot :muu 1 :ostoenergia-nettoala-kertoimella]
    [:tulokset :kaytettavat-energiamuodot :muu 2 :nimi]
    [:tulokset :kaytettavat-energiamuodot :muu 2 :ostoenergia]
    [:tulokset :kaytettavat-energiamuodot :muu 2 :muotokerroin]
    [:tulokset :kaytettavat-energiamuodot :muu 2 :ostoenergia-nettoala]
    [:tulokset :kaytettavat-energiamuodot :muu 2 :ostoenergia-kertoimella]
    [:tulokset :kaytettavat-energiamuodot :muu 2 :ostoenergia-nettoala-kertoimella]
    [:tulokset :kaytettavat-energiamuodot :summa]
    [:tulokset :kaytettavat-energiamuodot :kertoimella-summa]
    [:tulokset :uusiutuvat-omavaraisenergiat :aurinkosahko]
    [:tulokset :uusiutuvat-omavaraisenergiat :aurinkosahko-nettoala]
    [:tulokset :uusiutuvat-omavaraisenergiat :aurinkolampo]
    [:tulokset :uusiutuvat-omavaraisenergiat :aurinkolampo-nettoala]
    [:tulokset :uusiutuvat-omavaraisenergiat :tuulisahko]
    [:tulokset :uusiutuvat-omavaraisenergiat :tuulisahko-nettoala]
    [:tulokset :uusiutuvat-omavaraisenergiat :lampopumppu]
    [:tulokset :uusiutuvat-omavaraisenergiat :lampopumppu-nettoala]
    [:tulokset :uusiutuvat-omavaraisenergiat :muusahko]
    [:tulokset :uusiutuvat-omavaraisenergiat :muusahko-nettoala]
    [:tulokset :uusiutuvat-omavaraisenergiat :muulampo]
    [:tulokset :uusiutuvat-omavaraisenergiat :muulampo-nettoala]
    [:tulokset :uusiutuvat-omavaraisenergiat 0 :nimi-fi]
    [:tulokset :uusiutuvat-omavaraisenergiat 0 :nimi-sv]
    [:tulokset :uusiutuvat-omavaraisenergiat 0 :vuosikulutus]
    [:tulokset :uusiutuvat-omavaraisenergiat 0 :vuosikulutus-nettoala]
    [:tulokset :uusiutuvat-omavaraisenergiat 1 :nimi-fi]
    [:tulokset :uusiutuvat-omavaraisenergiat 1 :nimi-sv]
    [:tulokset :uusiutuvat-omavaraisenergiat 1 :vuosikulutus]
    [:tulokset :uusiutuvat-omavaraisenergiat 1 :vuosikulutus-nettoala]
    [:tulokset :uusiutuvat-omavaraisenergiat 2 :nimi-fi]
    [:tulokset :uusiutuvat-omavaraisenergiat 2 :nimi-sv]
    [:tulokset :uusiutuvat-omavaraisenergiat 2 :vuosikulutus]
    [:tulokset :uusiutuvat-omavaraisenergiat 2 :vuosikulutus-nettoala]
    [:tulokset :uusiutuvat-omavaraisenergiat 3 :nimi-fi]
    [:tulokset :uusiutuvat-omavaraisenergiat 3 :nimi-sv]
    [:tulokset :uusiutuvat-omavaraisenergiat 3 :vuosikulutus]
    [:tulokset :uusiutuvat-omavaraisenergiat 3 :vuosikulutus-nettoala]
    [:tulokset :uusiutuvat-omavaraisenergiat 4 :nimi-fi]
    [:tulokset :uusiutuvat-omavaraisenergiat 4 :nimi-sv]
    [:tulokset :uusiutuvat-omavaraisenergiat 4 :vuosikulutus]
    [:tulokset :uusiutuvat-omavaraisenergiat 4 :vuosikulutus-nettoala]
    [:tulokset :uusiutuvat-omavaraisenergiat 5 :nimi-fi]
    [:tulokset :uusiutuvat-omavaraisenergiat 5 :nimi-sv]
    [:tulokset :uusiutuvat-omavaraisenergiat 5 :vuosikulutus]
    [:tulokset :uusiutuvat-omavaraisenergiat 5 :vuosikulutus-nettoala]
    [:tulokset :tekniset-jarjestelmat :tilojen-lammitys :sahko]
    [:tulokset :tekniset-jarjestelmat :tilojen-lammitys :lampo]
    [:tulokset :tekniset-jarjestelmat :tuloilman-lammitys :sahko]
    [:tulokset :tekniset-jarjestelmat :tuloilman-lammitys :lampo]
    [:tulokset :tekniset-jarjestelmat :kayttoveden-valmistus :sahko]
    [:tulokset :tekniset-jarjestelmat :kayttoveden-valmistus :lampo]
    [:tulokset :tekniset-jarjestelmat :iv-sahko]
    [:tulokset :tekniset-jarjestelmat :jaahdytys :sahko]
    [:tulokset :tekniset-jarjestelmat :jaahdytys :lampo]
    [:tulokset :tekniset-jarjestelmat :jaahdytys :kaukojaahdytys]
    [:tulokset :tekniset-jarjestelmat :kuluttajalaitteet-ja-valaistus-sahko]
    [:tulokset :tekniset-jarjestelmat :sahko-summa]
    [:tulokset :tekniset-jarjestelmat :lampo-summa]
    [:tulokset :tekniset-jarjestelmat :kaukojaahdytys-summa]
    [:tulokset :nettotarve :tilojen-lammitys-vuosikulutus]
    [:tulokset :nettotarve :tilojen-lammitys-vuosikulutus-nettoala]
    [:tulokset :nettotarve :ilmanvaihdon-lammitys-vuosikulutus]
    [:tulokset :nettotarve :ilmanvaihdon-lammitys-vuosikulutus-nettoala]
    [:tulokset :nettotarve :kayttoveden-valmistus-vuosikulutus]
    [:tulokset :nettotarve :kayttoveden-valmistus-vuosikulutus-nettoala]
    [:tulokset :nettotarve :jaahdytys-vuosikulutus]
    [:tulokset :nettotarve :jaahdytys-vuosikulutus-nettoala]
    [:tulokset :lampokuormat :aurinko]
    [:tulokset :lampokuormat :aurinko-nettoala]
    [:tulokset :lampokuormat :ihmiset]
    [:tulokset :lampokuormat :ihmiset-nettoala]
    [:tulokset :lampokuormat :kuluttajalaitteet]
    [:tulokset :lampokuormat :kuluttajalaitteet-nettoala]
    [:tulokset :lampokuormat :valaistus]
    [:tulokset :lampokuormat :valaistus-nettoala]
    [:tulokset :lampokuormat :kvesi]
    [:tulokset :lampokuormat :kvesi-nettoala]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :kaukolampo-vuosikulutus]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :kaukolampo-vuosikulutus-nettoala]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :kokonaissahko-vuosikulutus]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :kokonaissahko-vuosikulutus-nettoala]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :kiinteistosahko-vuosikulutus]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :kiinteistosahko-vuosikulutus-nettoala]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :kayttajasahko-vuosikulutus]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :kayttajasahko-vuosikulutus-nettoala]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :kaukojaahdytys-vuosikulutus]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :kaukojaahdytys-vuosikulutus-nettoala]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :muu 0 :nimi-fi]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :muu 0 :nimi-sv]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :muu 0 :vuosikulutus]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :muu 0 :vuosikulutus-nettoala]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :muu 1 :nimi-fi]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :muu 1 :nimi-sv]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :muu 1 :vuosikulutus]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :muu 1 :vuosikulutus-nettoala]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :muu 2 :nimi-fi]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :muu 2 :nimi-sv]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :muu 2 :vuosikulutus]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :muu 2 :vuosikulutus-nettoala]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :muu 3 :nimi-fi]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :muu 3 :nimi-sv]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :muu 3 :vuosikulutus]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :muu 3 :vuosikulutus-nettoala]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :muu 4 :nimi-fi]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :muu 4 :nimi-sv]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :muu 4 :vuosikulutus]
    [:toteutunut-ostoenergiankulutus :ostettu-energia :muu 4 :vuosikulutus-nettoala]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :kevyt-polttooljy]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :kevyt-polttooljy-kerroin]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :kevyt-polttooljy-kwh]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :kevyt-polttooljy-kwh-nettoala]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :pilkkeet-havu-sekapuu]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :pilkkeet-havu-sekapuu-kerroin]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :pilkkeet-havu-sekapuu-kwh]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :pilkkeet-havu-sekapuu-kwh-nettoala]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :pilkkeet-koivu]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :pilkkeet-koivu-kerroin]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :pilkkeet-koivu-kwh]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :pilkkeet-koivu-kwh-nettoala]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :puupelletit]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :puupelletit-kerroin]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :puupelletit-kwh]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :puupelletit-kwh-nettoala]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :muu 0 :nimi]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :muu 0 :maara-vuodessa]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :muu 0 :yksikko]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :muu 0 :muunnoskerroin]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :muu 0 :kwh]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :muu 0 :kwh-nettoala]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :muu 1 :nimi]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :muu 1 :maara-vuodessa]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :muu 1 :yksikko]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :muu 1 :muunnoskerroin]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :muu 1 :kwh]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :muu 1 :kwh-nettoala]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :muu 2 :nimi]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :muu 2 :maara-vuodessa]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :muu 2 :yksikko]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :muu 2 :muunnoskerroin]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :muu 2 :kwh]
    [:toteutunut-ostoenergiankulutus :ostetut-polttoaineet :muu 2 :kwh-nettoala]
    [:toteutunut-ostoenergiankulutus :sahko-vuosikulutus-yhteensa]
    [:toteutunut-ostoenergiankulutus :sahko-vuosikulutus-yhteensa-nettoala]
    [:toteutunut-ostoenergiankulutus :kaukolampo-vuosikulutus-yhteensa]
    [:toteutunut-ostoenergiankulutus :kaukolampo-vuosikulutus-yhteensa-nettoala]
    [:toteutunut-ostoenergiankulutus :polttoaineet-vuosikulutus-yhteensa]
    [:toteutunut-ostoenergiankulutus :polttoaineet-vuosikulutus-yhteensa-nettoala]
    [:toteutunut-ostoenergiankulutus :kaukojaahdytys-vuosikulutus-yhteensa]
    [:toteutunut-ostoenergiankulutus :kaukojaahdytys-vuosikulutus-yhteensa-nettoala]
    [:toteutunut-ostoenergiankulutus :summa]
    [:toteutunut-ostoenergiankulutus :summa-nettoala]
    [:huomiot :ymparys :teksti-fi]
    [:huomiot :ymparys :teksti-sv]
    [:huomiot :ymparys :toimenpide 0 :nimi-fi]
    [:huomiot :ymparys :toimenpide 0 :nimi-sv]
    [:huomiot :ymparys :toimenpide 0 :lampo]
    [:huomiot :ymparys :toimenpide 0 :sahko]
    [:huomiot :ymparys :toimenpide 0 :jaahdytys]
    [:huomiot :ymparys :toimenpide 0 :eluvun-muutos]
    [:huomiot :ymparys :toimenpide 1 :nimi-fi]
    [:huomiot :ymparys :toimenpide 1 :nimi-sv]
    [:huomiot :ymparys :toimenpide 1 :lampo]
    [:huomiot :ymparys :toimenpide 1 :sahko]
    [:huomiot :ymparys :toimenpide 1 :jaahdytys]
    [:huomiot :ymparys :toimenpide 1 :eluvun-muutos]
    [:huomiot :ymparys :toimenpide 2 :nimi-fi]
    [:huomiot :ymparys :toimenpide 2 :nimi-sv]
    [:huomiot :ymparys :toimenpide 2 :lampo]
    [:huomiot :ymparys :toimenpide 2 :sahko]
    [:huomiot :ymparys :toimenpide 2 :jaahdytys]
    [:huomiot :ymparys :toimenpide 2 :eluvun-muutos]
    [:huomiot :alapohja-ylapohja :teksti-fi]
    [:huomiot :alapohja-ylapohja :teksti-sv]
    [:huomiot :alapohja-ylapohja :toimenpide 0 :nimi-fi]
    [:huomiot :alapohja-ylapohja :toimenpide 0 :nimi-sv]
    [:huomiot :alapohja-ylapohja :toimenpide 0 :lampo]
    [:huomiot :alapohja-ylapohja :toimenpide 0 :sahko]
    [:huomiot :alapohja-ylapohja :toimenpide 0 :jaahdytys]
    [:huomiot :alapohja-ylapohja :toimenpide 0 :eluvun-muutos]
    [:huomiot :alapohja-ylapohja :toimenpide 1 :nimi-fi]
    [:huomiot :alapohja-ylapohja :toimenpide 1 :nimi-sv]
    [:huomiot :alapohja-ylapohja :toimenpide 1 :lampo]
    [:huomiot :alapohja-ylapohja :toimenpide 1 :sahko]
    [:huomiot :alapohja-ylapohja :toimenpide 1 :jaahdytys]
    [:huomiot :alapohja-ylapohja :toimenpide 1 :eluvun-muutos]
    [:huomiot :alapohja-ylapohja :toimenpide 2 :nimi-fi]
    [:huomiot :alapohja-ylapohja :toimenpide 2 :nimi-sv]
    [:huomiot :alapohja-ylapohja :toimenpide 2 :lampo]
    [:huomiot :alapohja-ylapohja :toimenpide 2 :sahko]
    [:huomiot :alapohja-ylapohja :toimenpide 2 :jaahdytys]
    [:huomiot :alapohja-ylapohja :toimenpide 2 :eluvun-muutos]
    [:huomiot :lammitys :teksti-fi]
    [:huomiot :lammitys :teksti-sv]
    [:huomiot :lammitys :toimenpide 0 :nimi-fi]
    [:huomiot :lammitys :toimenpide 0 :nimi-sv]
    [:huomiot :lammitys :toimenpide 0 :lampo]
    [:huomiot :lammitys :toimenpide 0 :sahko]
    [:huomiot :lammitys :toimenpide 0 :jaahdytys]
    [:huomiot :lammitys :toimenpide 0 :eluvun-muutos]
    [:huomiot :lammitys :toimenpide 1 :nimi-fi]
    [:huomiot :lammitys :toimenpide 1 :nimi-sv]
    [:huomiot :lammitys :toimenpide 1 :lampo]
    [:huomiot :lammitys :toimenpide 1 :sahko]
    [:huomiot :lammitys :toimenpide 1 :jaahdytys]
    [:huomiot :lammitys :toimenpide 1 :eluvun-muutos]
    [:huomiot :lammitys :toimenpide 2 :nimi-fi]
    [:huomiot :lammitys :toimenpide 2 :nimi-sv]
    [:huomiot :lammitys :toimenpide 2 :lampo]
    [:huomiot :lammitys :toimenpide 2 :sahko]
    [:huomiot :lammitys :toimenpide 2 :jaahdytys]
    [:huomiot :lammitys :toimenpide 2 :eluvun-muutos]
    [:huomiot :iv-ilmastointi :teksti-fi]
    [:huomiot :iv-ilmastointi :teksti-sv]
    [:huomiot :iv-ilmastointi :toimenpide 0 :nimi-fi]
    [:huomiot :iv-ilmastointi :toimenpide 0 :nimi-sv]
    [:huomiot :iv-ilmastointi :toimenpide 0 :lampo]
    [:huomiot :iv-ilmastointi :toimenpide 0 :sahko]
    [:huomiot :iv-ilmastointi :toimenpide 0 :jaahdytys]
    [:huomiot :iv-ilmastointi :toimenpide 0 :eluvun-muutos]
    [:huomiot :iv-ilmastointi :toimenpide 1 :nimi-fi]
    [:huomiot :iv-ilmastointi :toimenpide 1 :nimi-sv]
    [:huomiot :iv-ilmastointi :toimenpide 1 :lampo]
    [:huomiot :iv-ilmastointi :toimenpide 1 :sahko]
    [:huomiot :iv-ilmastointi :toimenpide 1 :jaahdytys]
    [:huomiot :iv-ilmastointi :toimenpide 1 :eluvun-muutos]
    [:huomiot :iv-ilmastointi :toimenpide 2 :nimi-fi]
    [:huomiot :iv-ilmastointi :toimenpide 2 :nimi-sv]
    [:huomiot :iv-ilmastointi :toimenpide 2 :lampo]
    [:huomiot :iv-ilmastointi :toimenpide 2 :sahko]
    [:huomiot :iv-ilmastointi :toimenpide 2 :jaahdytys]
    [:huomiot :iv-ilmastointi :toimenpide 2 :eluvun-muutos]
    [:huomiot :valaistus-muut :teksti-fi]
    [:huomiot :valaistus-muut :teksti-sv]
    [:huomiot :valaistus-muut :toimenpide 0 :nimi-fi]
    [:huomiot :valaistus-muut :toimenpide 0 :nimi-sv]
    [:huomiot :valaistus-muut :toimenpide 0 :lampo]
    [:huomiot :valaistus-muut :toimenpide 0 :sahko]
    [:huomiot :valaistus-muut :toimenpide 0 :jaahdytys]
    [:huomiot :valaistus-muut :toimenpide 0 :eluvun-muutos]
    [:huomiot :valaistus-muut :toimenpide 1 :nimi-fi]
    [:huomiot :valaistus-muut :toimenpide 1 :nimi-sv]
    [:huomiot :valaistus-muut :toimenpide 1 :lampo]
    [:huomiot :valaistus-muut :toimenpide 1 :sahko]
    [:huomiot :valaistus-muut :toimenpide 1 :jaahdytys]
    [:huomiot :valaistus-muut :toimenpide 1 :eluvun-muutos]
    [:huomiot :valaistus-muut :toimenpide 2 :nimi-fi]
    [:huomiot :valaistus-muut :toimenpide 2 :nimi-sv]
    [:huomiot :valaistus-muut :toimenpide 2 :lampo]
    [:huomiot :valaistus-muut :toimenpide 2 :sahko]
    [:huomiot :valaistus-muut :toimenpide 2 :jaahdytys]
    [:huomiot :valaistus-muut :toimenpide 2 :eluvun-muutos]
    [:huomiot :suositukset-fi]
    [:huomiot :suositukset-sv]
    [:huomiot :lisatietoja-fi]
    [:huomiot :lisatietoja-sv]
    [:lisamerkintoja-fi]
    [:lisamerkintoja-sv]))

(t/deftest csv-snapshots-test
  (t/testing "Private columns are what we expect"
    (t/is (= expected-private-columns (vec csv/private-columns))))
  (t/testing "Public columns are what we expect"
    (t/is (= expected-public-columns (vec csv/public-columns))))
  (t/testing "Bank columns are what we expect"
    (t/is (= expected-bank-columns (vec csv/bank-columns))))
  (t/testing "Anonymized columns are what we expect"
    (t/is (= expected-anonymized-columns (vec csv/anonymized-columns))))
  (t/testing "Tilastokeskus columns are what we expect"
    (t/is (= expected-tilastokeskus-columns (vec csv/tilastokeskus-columns)))))
