(ns solita.etp.service.kayttaja-test
  (:require [clojure.test :as t]
            [schema.core :as schema]
            [solita.common.map :as map]
            [solita.common.time :as time]
            [solita.etp.test-system :as ts]
            [solita.etp.test-data.kayttaja :as kayttaja-test-data]
            [solita.etp.test-data.laatija :as laatija-test-data]
            [solita.etp.service.kayttaja :as service]
            [solita.etp.service.whoami :as whoami-service]
            [solita.etp.service.rooli :as rooli-service]
            [solita.etp.schema.kayttaja :as kayttaja-schema]
            [solita.etp.schema.laatija :as laatija-schema]
            [solita.etp.schema.common :as common-schema]))

(t/use-fixtures :each ts/fixture)

(defn test-data-set []
  {:kayttajat (kayttaja-test-data/generate-and-insert! 200)})

(t/deftest add-and-find-test
  ;; Every kayttaja generated by test-data-set has a non-laatija rooli
  ;; (patevyyden-toteaja, paakayttaja or laskuttaja), so laskuttaja and
  ;; patevyyden-toteaja whoami:t are exercised separately in
  ;; find-kayttaja-laskuttaja-and-patevyydentoteaja-access-test below.
  (let [{:keys [kayttajat]} (test-data-set)]
    (doseq [[id kayttaja] kayttajat
            :let [whoami (rand-nth [kayttaja-test-data/paakayttaja
                                    {:id id}])
                  found (service/find-kayttaja-for ts/*db* whoami id)]]
      (schema/validate kayttaja-schema/Kayttaja found)
      (t/is (map/submap? (dissoc kayttaja :api-key) found)))))

(t/deftest add-and-find-no-permissions-test
  (let [{:keys [kayttajat]} (test-data-set)]
    (doseq [[id _] kayttajat]
      (t/is (thrown-with-msg?
              clojure.lang.ExceptionInfo
              #"Forbidden"
              (service/find-kayttaja-for ts/*db*
                                         (rand-nth [kayttaja-test-data/laatija
                                                    kayttaja-test-data/patevyyden-toteaja
                                                    kayttaja-test-data/laskuttaja])
                                         id))))))

(t/deftest find-kayttaja-laskuttaja-and-patevyydentoteaja-access-test
  (let [{:keys [kayttajat]} (test-data-set)
        [non-laatija-id _] (first kayttajat)
        [laatija-id laatija] (laatija-test-data/generate-and-insert!)]
    (doseq [whoami [kayttaja-test-data/laskuttaja
                    kayttaja-test-data/patevyyden-toteaja]]
      (t/testing (str whoami " sees a laatija-kohde and its henkilotunnus")
        (let [found (service/find-kayttaja-for ts/*db* whoami laatija-id)]
          (schema/validate kayttaja-schema/Kayttaja found)
          (t/is (some? (:henkilotunnus found)))
          (t/is (= (:henkilotunnus laatija) (:henkilotunnus found)))))
      (t/testing (str whoami " has no access to a non-laatija-kohde")
        (t/is (thrown-with-msg?
               clojure.lang.ExceptionInfo
               #"Forbidden"
               (service/find-kayttaja-for ts/*db* whoami non-laatija-id)))))))

(t/deftest update-and-find-test
  (let [{:keys [kayttajat]} (test-data-set)
        updates (kayttaja-test-data/generate-updates (count kayttajat))]
    (doseq [[[id kayttaja] update] (->> (interleave kayttajat updates)
                                        (partition 2))]
      (service/update-kayttaja! ts/*db*
                                kayttaja-test-data/paakayttaja
                                id
                                update)
      (let [found (service/find-kayttaja-for
                   ts/*db*
                   kayttaja-test-data/paakayttaja
                   id)]
        (schema/validate kayttaja-schema/Kayttaja found)
        (t/is (map/submap? (dissoc update :api-key) found))))))

(t/deftest update-and-find-no-permissions-test
  (let [{:keys [kayttajat]} (test-data-set)
        updates (kayttaja-test-data/generate-updates (count kayttajat))]
    (doseq [[[id kayttaja] update] (->> (interleave kayttajat updates)
                                        (partition 2))]
      (t/is (thrown-with-msg?
             clojure.lang.ExceptionInfo
             #"Forbidden"
             (service/update-kayttaja!
              ts/*db*
              (rand-nth [kayttaja-test-data/laatija
                         kayttaja-test-data/patevyyden-toteaja
                         kayttaja-test-data/laskuttaja])
              id
              update))))))

(defn- logged-out-at-of [email]
  (-> (whoami-service/find-whoami-including-internal-fields ts/*db* {:email email})
      :logged-out-at))

(t/deftest stamp-logout!-test
  (let [{:keys [kayttajat]} (test-data-set)
        [id other-id] (-> kayttajat keys sort)
        email (:email (get kayttajat id))
        other-email (:email (get kayttajat other-id))]

    (t/testing "stamping sets logged_out_at to a non-nil, now()-ish timestamp"
      (let [before (time/now)
            _ (service/stamp-logout! ts/*db* id)
            after (time/now)
            logged-out-at (logged-out-at-of email)]
        (t/is (some? logged-out-at))
        (t/is (true? (and (some? logged-out-at)
                          (not (.isBefore logged-out-at before))
                          (not (.isAfter logged-out-at after)))))))

    (t/testing "stamping a second time (double logout) advances logged_out_at rather than being a no-op"
      (let [first-stamp (logged-out-at-of email)]
        (Thread/sleep 5)
        (service/stamp-logout! ts/*db* id)
        (let [second-stamp (logged-out-at-of email)]
          (t/is (some? second-stamp))
          (t/is (true? (and (some? first-stamp)
                            (some? second-stamp)
                            (.isAfter second-stamp first-stamp)))))))

    (t/testing "stamping for an id that does not exist does not throw and does not affect other users"
      (let [other-before (logged-out-at-of other-email)]
        (t/is (nil? (service/stamp-logout! ts/*db* -1)))
        (t/is (= other-before (logged-out-at-of other-email)))))

    (t/testing "only the targeted kayttaja row is updated, other users are left untouched"
      (t/is (nil? (logged-out-at-of other-email))))

    (t/testing "stamping logout does not clear/modify login or cognito_id set by update-kayttaja-with-whoami!"
      (let [cognitoid (str "cognitoid-" (rand-int 1000000))
            _ (whoami-service/update-kayttaja-with-whoami! ts/*db* {:id other-id :cognitoid cognitoid})
            found-before (service/find-kayttaja ts/*db* other-id)
            _ (service/stamp-logout! ts/*db* other-id)
            found-after (service/find-kayttaja ts/*db* other-id)]
        (t/is (some? (logged-out-at-of other-email)))
        (t/is (= (:login found-before) (:login found-after)))
        (t/is (= cognitoid (:cognitoid found-after)))))))
