create table perusparannuspassi (
  id int generated by default as identity primary key,
  versio int not null,
  valid boolean not null,
  energiatodistus_id int unique not null references energiatodistus (id)
);

create table perusparannuspassi_vaihe (
  perusparannuspassi_id int not null references perusparannuspassi (id),
  vaihe_nro int not null,
  valid boolean not null,
  constraint ppp_vaihe_pk primary key (perusparannuspassi_id, vaihe_nro),
  constraint vaihe_unique_per_ppp unique (perusparannuspassi_id, vaihe_nro),
  constraint vaihe_nro_positive check (1 <= vaihe_nro and vaihe_nro <= 4)
);
