version: '3.7'

services:
  db:
    image: postgres
    command: postgres -c 'max_connections=500'
    volumes:
      - type: bind
        source: ./initdb
        target: /docker-entrypoint-initdb.d
        read_only: true
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: etp

  admin:
    image: dpage/pgadmin4
    ports:
      - 9090:80
    environment:
      PGADMIN_DEFAULT_PASSWORD: etp
      PGADMIN_DEFAULT_EMAIL: etp@solita.fi
