insert into toimenpide_ehdotus_group (id, label_fi, label_sv, ordinal)
values
    (0, 'Lämmitys', 'Uppvärmning', 1),
    (1, 'Lämmin käyttövesi', 'Varmt bruksvatten', 2),
    (2, 'Ilmanvaihto', 'Ventilation', 3),
    (3, 'Valaistus', 'Belysning', 4),
    (4, 'Jäähdytys', 'Kylning''', 5),
    (5, 'Uusiutuva energia', 'Förnybar energi', 6),
    (6, 'Ikkunat', 'Fönster', 7),
    (7, 'Ulko-ovet', 'Ytterdörrar', 8),
    (8, 'Yläpohja', 'Vindsbjälklag', 9),
    (9, 'Alapohja', 'Bottenbjälklag', 10),
    (10, 'Julkisivu', 'Fasad', 11),
    (11, 'Muut toimenpiteet', 'Övriga åtgärder', 12)
on conflict (id) do update set label_fi = excluded.label_fi,
                               label_sv = excluded.label_sv,
                               ordinal  = excluded.ordinal;

insert into toimenpide_ehdotus (id, label_fi, label_sv, ordinal, valid, group_id)
values (0, 'Siirtyminen kaukolämpöön', 'Övergång till fjärrvärme', 1, true, 0),
       (1, 'Maalämpöpumppu', 'Jordvärmepump', 2, true, 0),
       (2, 'Ilma-vesilämpöpumppu', 'Luft-vattenvärmepump', 3, true, 0),
       (51, 'Ilmalämpöpumppu', 'Ilmalämpöpumppu (sv)', 4, true, 0),
       (3, 'Poistoilmalämpöpumppu', 'Frånluftsvärmepump', 5, true, 0),
       (4, 'Muu lämpöpumppu', 'Annan värmepump', 6, true, 0),
       (5, 'Hybridilämmitys', 'Hybriduppvärmning', 7, true, 0),
       (6, 'Bioenergia', 'Bioenergi', 8, true, 0),
       (7, 'Muu lämmitystoimenpide', 'Annan uppvärmningsåtgärd', 9, true, 0),
       (8, 'Käyttövesivaraajan lisäys/muutos', 'Tillägg/ändring av varmvattenberedare', 10, true, 1),
       (9, 'Vakiopaineventtiili', 'Konstanttrycksventil', 11, true, 1),
       (10, 'Muu lämpimän käyttöveden toimenpide', 'Annan åtgärd för varmt bruksvatten', 12, true, 1),
       (11, 'Koneellisen ilmanvaihdon muutos', 'Ändring av mekanisk ventilation', 13, true, 2),
       (12, 'Lämmöntalteenoton lisäys/parannus', 'Ändring/förbättring av värmeåtervinning', 14, true, 2),
       (13, 'Ilmanvaihtokoneen uusiminen', 'Förnyande av ventilationsenhet', 15, true, 2),
       (14, 'Tarpeenmukainen ilmanvaihto', 'Behovsstyrd ventilation', 16, true, 2),
       (15, 'Muu ilmanvaihdon toimenpide', 'Annan ventilationsåtgärd', 17, true, 2),
       (16, 'Valaistuksen tehotiheyden muutos', 'Ändring av belysningens effekttäthet', 18, true, 3),
       (17, 'Tarpeenmukainen valaistus', 'Behovsstyrd belysning', 19, true, 3),
       (18, 'Muu valaistuksen toimenpide', 'Annan belysningsåtgärd', 20, true, 3),
       (19, 'Siirtyminen kaukojäähdytykseen', 'Övergång till fjärrkyla', 21, true, 4),
       (20, 'Jäähdytyskoneen muutos/uusiminen', 'Ändring/förnyande av kylluftsaggregat', 22, true, 4),
       (21, 'Passiivisen jäähdytyksen lisääminen', 'Tillägg av passiv kylning', 23, true, 4),
       (22, 'Muu jäähdytystoimenpide', 'Annan kylningsåtgärd', 24, true, 4),
       (23, 'Aurinkosähkö', 'Solel', 25, true, 5),
       (24, 'Aurinkolämpö', 'Solvärme', 26, true, 5),
       (25, 'Tuulivoima', 'Vindkraft', 27, true, 5),
       (26, 'Muu uusiutuvan energian toimenpide', 'Annan åtgärd för förnybar energi', 28, true, 5),
       (27, 'Muu ikkunatoimenpide', 'Annan fönsteråtgärd', 30, true, 6),
       (28, 'Muu ulko-ovitoimenpide', 'Annan ytterdörråtgärd', 32, true, 7),
       (29, 'Muu yläpohjan toimenpide', 'Annan åtgärd i vindsbjälklaget', 34, true, 8),
       (30, 'Muu alapohjan toimenpide', 'Annan åtgärd i bottenbjälklaget', 36, true, 9),
       (31, 'Tiiveyden parantaminen', 'Förbättring av täthet', 38, true, 10),
       (32, 'Muu julkisivun toimenpide', 'Annan fasadåtgärd', 39, true, 10),
       (33, 'Energian varastointi', 'Lagring av energi', 40, true, 11),
       (34, 'Kulutusjousto', 'Efterfrågeflexibilitet ', 41, true, 11),
       (35, 'Varaavat tulisijat', 'Eldstäder med långsam värmeavgivning', 37, false, 0),
       (36, 'Lämmönjaon hyötysuhteen muutos', 'Ändring av värmedistributionens verkningsgrad', 38, false, 0),
       (37, 'Lämmitysverkoston eristyksen muutos', 'Ändring av uppvärmningsnätets isolering', 39, false, 0),
       (38, 'Energiavaraajan muutos/lisäys', 'Ändring/tillägg av energiackumulator', 40, false, 0),
       (39, 'Lämmitysverkoston eristyksen muutos', 'Ändring av uppvärmningsnätets isolering', 41, false, 0),
       (40, 'Märkätilojen lämmityksen muutos', 'Ändring av uppvärmning för våtrum', 42, false, 0),
       (41, 'Lämmin käyttövesi', 'Varmt bruksvatten', 43, false, 1),
       (42, 'Lämpimän käyttövesiverkoston eristyksen muutos', 'Ändring av isolering av nätverket för varmt bruksvatten', 44, false, 1),
       (43, 'Lämpimän käyttöveden kiertojohdon muutos', 'Ändring av cirkulationsledning för varmt bruksvatten', 45, false, 1),
       (44, 'Painovoimaisen IV:n muutos koneelliseksi', 'Ändring från självdragsventilation till mekanisk ventilation', 46, false, 2),
       (45, 'Jäteveden lämmöntalteenotto', 'Värmeåtervinning från avloppsvatten', 47, false, 1),
       (46, 'Ikkunoiden uusiminen', 'Förnyande av fönster', 29, true, 6),
       (47, 'Ulko-ovien uusiminen', 'Förnyande av ytterdörrar', 31, true, 7),
       (48, 'Yläpohjan lisäeristys', 'Tilläggsisolering av vindsbjälklag', 33, true, 8),
       (49, 'Alapohjan lisäeristys', 'Tilläggsisolering av bottenbjälklag', 35, true, 9),
       (50, 'Julkisivun lisäeristys', 'Tilläggsisolering av fasad', 37, true, 10)


on conflict (id) do update set label_fi = excluded.label_fi,
                               label_sv = excluded.label_sv,
                               ordinal  = excluded.ordinal,
                               valid    = excluded.valid,
                               group_id = excluded.group_id;
