insert into toimenpide_ehdotus_group (id, label_fi, label_sv, ordinal)
values
    (0, 'Lämmitys', 'Lämmitys (sv)', 1),
    (1, 'Lämmin käyttövesi', 'Lämmin käyttövesi (sv)', 2),
    (2, 'Ilmanvaihto', 'Ilmanvaihto (sv)', 3),
    (3, 'Valaistus', 'Valaistus (sv)', 4),
    (4, 'Jäähdytys', 'Jäähdytys (sv)', 5),
    (5, 'Uusiutuva energia', 'Uusiutuva energia (sv)', 6),
    (6, 'Ikkunat', 'Ikkunat (sv)', 7),
    (7, 'Ulko-ovet', 'Ulko-ovet (sv)', 8),
    (8, 'Yläpohja', 'Yläpohja (sv)', 9),
    (9, 'Alapohja', 'Alapohja (sv)', 10),
    (10, 'Julkisivu', 'Julkisivu (sv)', 11),
    (11, 'Muut toimenpiteet', 'Muut toimenpiteet (sv)', 12)
on conflict (id) do update set label_fi = excluded.label_fi,
                               label_sv = excluded.label_sv,
                               ordinal  = excluded.ordinal;

insert into toimenpide_ehdotus (id, label_fi, label_sv, ordinal, valid, group_id)
values (0, 'Siirtyminen kaukolämpöön', 'Siirtyminen kaukolämpöön (sv)', 1, true, 0),
       (1, 'Maalämpöpumppu', 'Maalämpöpumppu (sv)', 2, true, 0),
       (2, 'Ilma-vesilämpöpumppu', 'Ilma-vesilämpöpumppu (sv)', 3, true, 0),
       (3, 'Poistoilmalämpöpumppu', 'Poistoilmalämpöpumppu (sv)', 4, true, 0),
       (4, 'Muu lämpöpumppu', 'Muu lämpöpumppu (sv)', 5, true, 0),
       (5, 'Hybridilämmitys', 'Hybridilämmitys (sv)', 6, true, 0),
       (6, 'Bioenergia', 'Bioenergia (sv)', 7, true, 0),
       (7, 'Muu lämmitystoimenpide', 'Muu lämmitystoimenpide (sv)', 8, true, 0),
       (8, 'Käyttövesivaraajan lisäys/muutos', 'Käyttövesivaraajan lisäys/muutos (sv)', 9, true, 1),
       (9, 'Vakiopaineventtiili', 'Vakiopaineventtiili (sv)', 10, true, 1),
       (10, 'Muu lämpimän käyttöveden toimenpide', 'Muu lämpimän käyttöveden toimenpide (sv)', 11, true, 1),
       (11, 'Koneellisen ilmanvaihdon muutos', 'Koneellisen ilmanvaihdon muutos (sv)', 12, true, 2),
       (12, 'Lämmöntalteenoton lisäys/parannus', 'Lämmöntalteenoton lisäys/parannus (sv)', 13, true, 2),
       (13, 'Ilmanvaihtokoneen uusiminen', 'Ilmanvaihtokoneen uusiminen (sv)', 14, true, 2),
       (14, 'Tarpeenmukainen ilmanvaihto', 'Tarpeenmukainen ilmanvaihto (sv)', 15, true, 2),
       (15, 'Muu ilmanvaihdon toimenpide', 'Muu ilmanvaihdon toimenpide (sv)', 16, true, 2),
       (16, 'Valaistuksen tehotiheyden muutos', 'Valaistuksen tehotiheyden muutos (sv)', 17, true, 3),
       (17, 'Tarpeenmukainen valaistus', 'Tarpeenmukainen valaistus (sv)', 18, true, 3),
       (18, 'Muu valaistuksen toimenpide', 'Muu valaistuksen toimenpide (sv)', 19, true, 3),
       (19, 'Siirtyminen kaukojäähdytykseen', 'Siirtyminen kaukojäähdytykseen (sv)', 20, true, 4),
       (20, 'Jäähdytyskoneen muutos/uusiminen', 'Jäähdytyskoneen muutos/uusiminen (sv)', 21, true, 4),
       (21, 'Passiivisen jäähdytyksen lisääminen', 'Passiivisen jäähdytyksen lisääminen (sv)', 22, true, 4),
       (22, 'Muu jäähdytystoimenpide', 'Muu jäähdytystoimenpide (sv)', 23, true, 4),
       (23, 'Aurinkosähkö', 'Aurinkosähkö (sv)', 24, true, 5),
       (24, 'Aurinkolämpö', 'Aurinkolämpö (sv)', 25, true, 5),
       (25, 'Tuulivoima', 'Tuulivoima (sv)', 26, true, 5),
       (26, 'Muu uusiutuvan energian toimenpide', 'Muu uusiutuvan energian toimenpide (sv)', 27, true, 5),
       (27, 'Muu ikkunatoimenpide', 'Muu ikkunatoimenpide (sv)', 29, true, 6),
       (28, 'Muu ulko-ovitoimenpide', 'Muu ulko-ovitoimenpide (sv)', 31, true, 7),
       (29, 'Muu yläpohjan toimenpide', 'Muu yläpohjan toimenpide (sv)', 33, true, 8),
       (30, 'Muu alapohjan toimenpide', 'Muu alapohjan toimenpide (sv)', 35, true, 9),
       (31, 'Tiiveyden parantaminen', 'Tiiveyden parantaminen (sv)', 37, true, 10),
       (32, 'Muu julkisivun toimenpide', 'Muu julkisivun toimenpide (sv)', 38, true, 10),
       (33, 'Energian varastointi', 'Energian varastointi (sv)', 39, true, 11),
       (34, 'Kulutusjousto', 'Kulutusjousto (sv)', 40, true, 11),
       (35, 'Varaavat tulisijat', 'Varaavat tulisijat (sv)', 36, false, 0),
       (36, 'Lämmönjaon hyötysuhteen muutos', 'Lämmönjaon hyötysuhteen muutos (sv)', 37, false, 0),
       (37, 'Lämmitysverkoston eristyksen muutos', 'Lämmitysverkoston eristyksen muutos (sv)', 38, false, 0),
       (38, 'Energiavaraajan muutos/lisäys', 'Energiavaraajan muutos/lisäys (sv)', 39, false, 0),
       (39, 'Lämmitysverkoston eristyksen muutos', 'Lämmitysverkoston eristyksen muutos (sv)', 40, false, 0),
       (40, 'Märkätilojen lämmityksen muutos', 'Märkätilojen lämmityksen muutos (sv)', 41, false, 0),
       (41, 'Lämmin käyttövesi', 'Lämmin käyttövesi (sv)', 42, false, 1),
       (42, 'Lämpimän käyttövesiverkoston eristyksen muutos', 'Lämpimän käyttövesiverkoston eristyksen muutos (sv)', 43, false, 1),
       (43, 'Lämpimän käyttöveden kiertojohdon muutos', 'Lämpimän käyttöveden kiertojohdon muutos (sv)', 44, false, 1),
       (44, 'Painovoimaisen IV:n muutos koneelliseksi', 'Painovoimaisen IV:n muutos koneelliseksi (sv)', 45, false, 2),
       (45, 'Jäteveden lämmöntalteenotto', 'Jäteveden lämmöntalteenotto (sv)', 46, false, 1),
       (46, 'Ikkunoiden uusiminen', 'Ikkunoiden uusiminen (sv)', 28, true, 6),
       (47, 'Ulko-ovien uusiminen', 'Ulko-ovien uusiminen (sv)', 30, true, 7),
       (48, 'Yläpohjan lisäeristys', 'Yläpohjan lisäeristys (sv)', 32, true, 8),
       (49, 'Alapohjan lisäeristys', 'Alapohjan lisäeristys (sv)', 34, true, 9),
       (50, 'Julkisivun lisäeristys', 'Julkisivun lisäeristys (sv)', 36, true, 10)

on conflict (id) do update set label_fi = excluded.label_fi,
                               label_sv = excluded.label_sv,
                               ordinal  = excluded.ordinal,
                               valid    = excluded.valid,
                               group_id = excluded.group_id;
