name: 'etp'

services:
  db:
    image: postgres:15.8-alpine
    command: postgres -c 'max_connections=500'
    volumes:
      - type: bind
        source: ./initdb
        target: /docker-entrypoint-initdb.d
        read_only: true
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_PASSWORD: etp
    healthcheck:
      test: pg_isready -U postgres
      interval: 1s
      timeout: 5s
      retries: 30

  etp-db-for-etp_dev:
    build: ../../etp-core/etp-db
    image: etp-db
    environment:
      DB_URL: jdbc:postgresql://db:5432/etp_dev
    command:
      ./db.sh migrate test
    depends_on:
      db:
        condition: service_healthy

  etp-db-for-postgres:
    image: etp-db
    environment:
      DB_URL: jdbc:postgresql://db:5432/postgres
    command:
      ./db.sh migrate
    depends_on:
      db:
        condition: service_healthy

  admin:
    image: dpage/pgadmin4
    ports:
      - 127.0.0.1:9090:80
    environment:
      PGADMIN_DEFAULT_PASSWORD: etp
      PGADMIN_DEFAULT_EMAIL: etp@solita.fi

  minio:
    image: minio/minio:RELEASE.2024-02-17T01-15-57Z
    ports:
      - 127.0.0.1:9002:9000
      - 127.0.0.1:9001:9001
    networks:
      - minio
    volumes:
      - data:/files
    command: server /files --console-address ":9001"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123

  minio_create_default_bucket:
    image: minio/mc:latest
    depends_on:
      minio:
        condition: service_started
    networks:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      /usr/bin/mc alias set local http://minio:9000 minio minio123 --api S3v4;
      /usr/bin/mc mb local/files --region=eu-central-1;
      /usr/bin/mc policy set public local/files;
      "
  sftp:
    build: ./sftp
    ports:
      - 127.0.0.1:2222:22

  smtp:
    build: ./smtp
    ports:
      - 127.0.0.1:2525:25
    volumes:
      - type: bind
        source: ./smtp/received-emails
        target: /received-emails

  ocsp-responder-int:
    build: ./ocsp-test-pki
    ports:
      - 127.0.0.1:2061:2060
    volumes:
      - type: bind
        source: ./ocsp-test-pki/pki-int
        target: /etc/pki
        read_only: true

  ocsp-responder-root:
    build: ./ocsp-test-pki
    ports:
      - 127.0.0.1:2060:2060
    volumes:
      - type: bind
        source: ./ocsp-test-pki/pki-root
        target: /etc/pki
        read_only: true

  kms:
    image: nsmithuk/local-kms:3.12.0
    ports:
      - 127.0.0.1:8899:8080
    volumes:
      - type: bind
        source: ./kms
        target: /init
        read_only: true

volumes:
  data:

networks:
  minio:
