version: '3.7'

services:
  backend:
    build: ../../etp-core/etp-backend
    environment:
        # solita.etp.config
      DB_HOST: db
      SMTP_HOST: smtp
      LASKUTUS_SFTP_HOST: sftp
      # TODO: Täytyy muutta envistä luettavaksi. Ehkä.
      # S3:
    env_file: 
      - ./backend.env
    expose:
      - "8080"

        # frontend-private:
        #   image: 
