-- name: select-expired-energiatodistus-ids
select id as energiatodistus_id
from energiatodistus
         left join (select max(create_time) as latest_toimenpide_create_time, energiatodistus_id
                    from vo_toimenpide
                    group by energiatodistus_id) latest_toimenpide
                   on energiatodistus.id = latest_toimenpide.energiatodistus_id
where voimassaolo_paattymisaika < current_date
  and (latest_toimenpide_create_time < current_date - interval '2 years'
    or latest_toimenpide_create_time is null);

-- name: select-vo-toimenpiteet-by-energiatodistus-id
select id as vo_toimenpide_id
from vo_toimenpide
where energiatodistus_id = :energiatodistus_id;

-- name: select-to-be-destroyed-liitteet-by-energiatodistus-id
select id
from liite
where energiatodistus_id = :energiatodistus_id;

-- name: select-liitteet-by-viestiketju-id
select id as viesti_liite_id
from viesti_liite
where viestiketju_id = :viestiketju_id;

-- name: select-viestiketjut-by-energiatodistus-id
select id as viestiketju_id
from viestiketju
where energiatodistus_id = :energiatodistus_id;

-- name: select-viestiketjut-by-oikeellisuuden-valvonta
select id as viestiketju_id
from viestiketju
where vo_toimenpide_id = :vo_toimenpide_id;

-- name: select-viestit-by-viestiketju
select id as viesti_id
from viesti
where viestiketju_id = :viestiketju_id;

-- name: destroy-energiatodistus-oikeellisuuden-valvonta-toimenpide!
delete
from vo_toimenpide
where energiatodistus_id = :energiatodistus_id;

-- name: destroy-energiatodistus-oikeellisuuden-valvonta-toimenpide-audit!
delete
from audit.vo_toimenpide
where energiatodistus_id = :energiatodistus_id;

-- name: destroy-energiatodistus-oikeellisuuden-valvonta-note!
delete
from vo_note
where energiatodistus_id = :energiatodistus_id;

-- name: destroy-energiatodistus-oikeellisuuden-valvonta-note-audit!
delete
from audit.vo_note
where energiatodistus_id = :energiatodistus_id;

-- name: destroy-energiatodistus-oikeellisuuden-valvonta-virhe!
delete
from vo_virhe
where toimenpide_id in (select id from vo_toimenpide where energiatodistus_id = :energiatodistus_id);

-- name: destroy-energiatodistus-oikeellisuuden-valvonta-tiedoksi!
delete
from vo_tiedoksi
where toimenpide_id in (select id from vo_toimenpide where energiatodistus_id = :energiatodistus_id);

-- name: destroy-liite!
delete
from liite
where id = :liite_id;

-- name: destroy-liite-audit!
delete
from audit.liite
where id = :liite_id;

-- name: destroy-viesti-reader!
delete
from viesti_reader
where viesti_id = :viesti_id;

-- name: destroy-viestiketju-liite!
delete
from viesti_liite
where viestiketju_id = :viestiketju_id;

-- name: destroy-viestiketju-liite-audit!
delete
from audit.viesti_liite
where viestiketju_id = :viestiketju_id;

-- name: destroy-viesti!
delete
from viesti
where id = :viesti_id;

-- name: destroy-viestiketju!
delete
from viestiketju
where id = :viestiketju_id;

-- name: destroy-viestiketju-audit!
delete
from audit.viestiketju
where id = :viestiketju_id;

-- name: destroy-vastaanottaja!
delete
from vastaanottaja
where viestiketju_id = :viestiketju_id;

-- name: destroy-energiatodistus-audit!
delete
from audit.energiatodistus
where id = :energiatodistus_id;

-- name: anonymize-energiatodistus!
update energiatodistus
set
    -- Keep the id.
    -- id int generated by default as identity primary key,
    -- Set versio to same in all todistus.
    versio                                                          = 2013,
    tila_id                                                         = 6, -- tuhottu
    allekirjoitusaika                                               = null,
    voimassaolo_paattymisaika                                       = null,
    -- Keep the link to laatija.
    --laatija_id int not null references laatija (id),
    laskutettava_yritys_id                                          = null,
    laskuriviviite                                                  = null,
    laskutusaika                                                    = null,
    -- Keep the korvaus link.
    -- korvattu_energiatodistus_id integer unique references energiatodistus (id),
    kommentti                                                       = null,
    valvonta                                                        = false,

    pt$havainnointikaynti                                           = null,
    pt$katuosoite_fi                                                = null,
    pt$katuosoite_sv                                                = null,
    pt$kayttotarkoitus                                              = null,
    pt$keskeiset_suositukset_fi                                     = null,
    pt$keskeiset_suositukset_sv                                     = null,
    pt$kieli                                                        = null,
    pt$kiinteistotunnus                                             = null,
    pt$laatimisvaihe                                                = null,
    pt$uudisrakennus                                                = false,
    pt$nimi                                                         = null,
    pt$julkinen_rakennus                                            = false,
    pt$postinumero                                                  = null,
    pt$rakennusosa                                                  = null,
    pt$rakennustunnus                                               = null,
    pt$tilaaja                                                      = null,
    pt$valmistumisvuosi                                             = null,
    pt$yritys$katuosoite                                            = null,
    pt$yritys$nimi                                                  = null,
    pt$yritys$postinumero                                           = null,
    pt$yritys$postitoimipaikka                                      = null,

    lt$ikkunat$etela$u                                              = null,
    lt$ikkunat$etela$ala                                            = null,
    lt$ikkunat$etela$g_ks                                           = null,
    lt$ikkunat$ita$u                                                = null,
    lt$ikkunat$ita$ala                                              = null,
    lt$ikkunat$ita$g_ks                                             = null,
    lt$ikkunat$kaakko$u                                             = null,
    lt$ikkunat$kaakko$ala                                           = null,
    lt$ikkunat$kaakko$g_ks                                          = null,
    lt$ikkunat$katto$u                                              = null,
    lt$ikkunat$katto$ala                                            = null,
    lt$ikkunat$katto$g_ks                                           = null,
    lt$ikkunat$koillinen$u                                          = null,
    lt$ikkunat$koillinen$ala                                        = null,
    lt$ikkunat$koillinen$g_ks                                       = null,
    lt$ikkunat$lansi$u                                              = null,
    lt$ikkunat$lansi$ala                                            = null,
    lt$ikkunat$lansi$g_ks                                           = null,
    lt$ikkunat$lounas$u                                             = null,
    lt$ikkunat$lounas$ala                                           = null,
    lt$ikkunat$lounas$g_ks                                          = null,
    lt$ikkunat$luode$u                                              = null,
    lt$ikkunat$luode$ala                                            = null,
    lt$ikkunat$luode$g_ks                                           = null,
    lt$ikkunat$pohjoinen$u                                          = null,
    lt$ikkunat$pohjoinen$ala                                        = null,
    lt$ikkunat$pohjoinen$g_ks                                       = null,
    lt$ikkunat$valokupu$u                                           = null,
    lt$ikkunat$valokupu$ala                                         = null,
    lt$ikkunat$valokupu$g_ks                                        = null,
    lt$ilmanvaihto$erillispoistot$poisto                            = null,
    lt$ilmanvaihto$erillispoistot$sfp                               = null,
    lt$ilmanvaihto$erillispoistot$tulo                              = null,
    lt$ilmanvaihto$ivjarjestelma$poisto                             = null,
    lt$ilmanvaihto$ivjarjestelma$sfp                                = null,
    lt$ilmanvaihto$ivjarjestelma$tulo                               = null,
    lt$ilmanvaihto$tyyppi_id                                        = null,
    lt$ilmanvaihto$kuvaus_fi                                        = null,
    lt$ilmanvaihto$kuvaus_sv                                        = null,
    lt$ilmanvaihto$lto_vuosihyotysuhde                              = null,
    lt$ilmanvaihto$tuloilma_lampotila                               = null,
    lt$ilmanvaihto$paaiv$jaatymisenesto                             = null,
    lt$ilmanvaihto$paaiv$lampotilasuhde                             = null,
    lt$ilmanvaihto$paaiv$poisto                                     = null,
    lt$ilmanvaihto$paaiv$sfp                                        = null,
    lt$ilmanvaihto$paaiv$tulo                                       = null,
    lt$jaahdytysjarjestelma$jaahdytyskauden_painotettu_kylmakerroin = null,
    lt$lammitetty_nettoala                                          = null,
    lt$lammitys$ilmalampopumppu$maara                               = null,
    lt$lammitys$ilmalampopumppu$tuotto                              = null,
    lt$lammitys$lammitysmuoto_1$id                                  = null,
    lt$lammitys$lammitysmuoto_1$kuvaus_fi                           = null,
    lt$lammitys$lammitysmuoto_1$kuvaus_sv                           = null,
    lt$lammitys$lammitysmuoto_2$id                                  = null,
    lt$lammitys$lammitysmuoto_2$kuvaus_fi                           = null,
    lt$lammitys$lammitysmuoto_2$kuvaus_sv                           = null,
    lt$lammitys$lammonjako$id                                       = null,
    lt$lammitys$lammonjako$kuvaus_fi                                = null,
    lt$lammitys$lammonjako$kuvaus_sv                                = null,
    lt$lammitys$lammin_kayttovesi$apulaitteet                       = null,
    lt$lammitys$lammin_kayttovesi$jaon_hyotysuhde                   = null,
    lt$lammitys$lammin_kayttovesi$lampokerroin                      = null,
    lt$lammitys$lammin_kayttovesi$tuoton_hyotysuhde                 = null,
    lt$lammitys$lammin_kayttovesi$lampohavio_lammittamaton_tila     = null,
    lt$lammitys$lammin_kayttovesi$lampopumppu_tuotto_osuus          = null,
    lt$lammitys$takka$maara                                         = null,
    lt$lammitys$takka$tuotto                                        = null,
    lt$lammitys$tilat_ja_iv$apulaitteet                             = null,
    lt$lammitys$tilat_ja_iv$jaon_hyotysuhde                         = null,
    lt$lammitys$tilat_ja_iv$lampokerroin                            = null,
    lt$lammitys$tilat_ja_iv$tuoton_hyotysuhde                       = null,
    lt$lammitys$tilat_ja_iv$lampohavio_lammittamaton_tila           = null,
    lt$lammitys$tilat_ja_iv$lampopumppu_tuotto_osuus                = null,
    lt$lkvn_kaytto$ominaiskulutus                                   = null,
    lt$lkvn_kaytto$lammitysenergian_nettotarve                      = null,
    lt$rakennusvaippa$ilmanvuotoluku                                = null,
    lt$rakennusvaippa$lampokapasiteetti                             = null,
    lt$rakennusvaippa$ilmatilavuus                                  = null,
    lt$rakennusvaippa$alapohja$u                                    = null,
    lt$rakennusvaippa$alapohja$ala                                  = null,
    lt$rakennusvaippa$ikkunat$u                                     = null,
    lt$rakennusvaippa$ikkunat$ala                                   = null,
    lt$rakennusvaippa$kylmasillat_UA                                = null,
    lt$rakennusvaippa$ulkoovet$u                                    = null,
    lt$rakennusvaippa$ulkoovet$ala                                  = null,
    lt$rakennusvaippa$ulkoseinat$u                                  = null,
    lt$rakennusvaippa$ulkoseinat$ala                                = null,
    lt$rakennusvaippa$ylapohja$u                                    = null,
    lt$rakennusvaippa$ylapohja$ala                                  = null,
    lt$sis_kuorma$henkilot$kayttoaste                               = null,
    lt$sis_kuorma$henkilot$lampokuorma                              = null,
    lt$sis_kuorma$kuluttajalaitteet$kayttoaste                      = null,
    lt$sis_kuorma$kuluttajalaitteet$lampokuorma                     = null,
    lt$sis_kuorma$valaistus$kayttoaste                              = null,
    lt$sis_kuorma$valaistus$lampokuorma                             = null,

    t$e_luku                                                        = null,
    t$e_luokka                                                      = null,
    t$kaytettavat_energiamuodot$fossiilinen_polttoaine              = null,
    t$kaytettavat_energiamuodot$kaukojaahdytys                      = null,
    t$kaytettavat_energiamuodot$kaukolampo                          = null,
    t$kaytettavat_energiamuodot$sahko                               = null,
    t$kaytettavat_energiamuodot$uusiutuva_polttoaine                = null,
    t$kaytettavat_energiamuodot$muu                                 = null,
    t$lampokuormat$aurinko                                          = null,
    t$lampokuormat$ihmiset                                          = null,
    t$lampokuormat$kuluttajalaitteet                                = null,
    t$lampokuormat$kvesi                                            = null,
    t$lampokuormat$valaistus                                        = null,
    t$laskentatyokalu                                               = null,
    t$nettotarve$ilmanvaihdon_lammitys_vuosikulutus                 = null,
    t$nettotarve$jaahdytys_vuosikulutus                             = null,
    t$nettotarve$kayttoveden_valmistus_vuosikulutus                 = null,
    t$nettotarve$tilojen_lammitys_vuosikulutus                      = null,
    t$tekniset_jarjestelmat$iv_sahko                                = null,
    t$tekniset_jarjestelmat$jaahdytys$kaukojaahdytys                = null,
    t$tekniset_jarjestelmat$jaahdytys$lampo                         = null,
    t$tekniset_jarjestelmat$jaahdytys$sahko                         = null,
    t$tekniset_jarjestelmat$kayttoveden_valmistus$lampo             = null,
    t$tekniset_jarjestelmat$kayttoveden_valmistus$sahko             = null,
    t$tekniset_jarjestelmat$kuluttajalaitteet_ja_valaistus_sahko    = null,
    t$tekniset_jarjestelmat$tilojen_lammitys$lampo                  = null,
    t$tekniset_jarjestelmat$tilojen_lammitys$sahko                  = null,
    t$tekniset_jarjestelmat$tuloilman_lammitys$lampo                = null,
    t$tekniset_jarjestelmat$tuloilman_lammitys$sahko                = null,
    t$uusiutuvat_omavaraisenergiat$aurinkolampo                     = null,
    t$uusiutuvat_omavaraisenergiat$aurinkosahko                     = null,
    t$uusiutuvat_omavaraisenergiat$lampopumppu                      = null,
    t$uusiutuvat_omavaraisenergiat$muulampo                         = null,
    t$uusiutuvat_omavaraisenergiat$muusahko                         = null,
    t$uusiutuvat_omavaraisenergiat$tuulisahko                       = null,
    t$uusiutuvat_omavaraisenergiat$muu                              = null,
    t$kuukausierittely                                              = null,

    to$kaukojaahdytys_vuosikulutus_yhteensa                         = null,
    to$kaukolampo_vuosikulutus_yhteensa                             = null,
    to$ostettu_energia$kaukojaahdytys_vuosikulutus                  = null,
    to$ostettu_energia$kaukolampo_vuosikulutus                      = null,
    to$ostettu_energia$kayttajasahko_vuosikulutus                   = null,
    to$ostettu_energia$kiinteistosahko_vuosikulutus                 = null,
    to$ostettu_energia$kokonaissahko_vuosikulutus                   = null,
    to$ostettu_energia$muu                                          = null,

    to$ostetut_polttoaineet$kevyt_polttooljy                        = null,
    to$ostetut_polttoaineet$pilkkeet_havu_sekapuu                   = null,
    to$ostetut_polttoaineet$pilkkeet_koivu                          = null,
    to$ostetut_polttoaineet$puupelletit                             = null,
    to$ostetut_polttoaineet$muu                                     = null,
    to$polttoaineet_vuosikulutus_yhteensa                           = null,
    to$sahko_vuosikulutus_yhteensa                                  = null,

    h$alapohja_ylapohja$teksti_fi                                   = null,
    h$alapohja_ylapohja$teksti_sv                                   = null,
    h$alapohja_ylapohja$toimenpide                                  = null,
    h$iv_ilmastointi$teksti_fi                                      = null,
    h$iv_ilmastointi$teksti_sv                                      = null,
    h$iv_ilmastointi$toimenpide                                     = null,
    h$lammitys$teksti_fi                                            = null,
    h$lammitys$teksti_sv                                            = null,
    h$lammitys$toimenpide                                           = null,
    h$valaistus_muut$teksti_fi                                      = null,
    h$valaistus_muut$teksti_sv                                      = null,
    h$valaistus_muut$toimenpide                                     = null,
    h$ymparys$teksti_fi                                             = null,
    h$ymparys$teksti_sv                                             = null,
    h$ymparys$toimenpide                                            = null,
    h$lisatietoja_fi                                                = null,
    h$lisatietoja_sv                                                = null,
    h$suositukset_fi                                                = null,
    h$suositukset_sv                                                = null,

    lisamerkintoja_fi                                               = null,
    lisamerkintoja_sv                                               = null,

    pt$nimi_fi                                                      = null,
    pt$nimi_sv                                                      = null,
    draft_visible_to_paakayttaja                                    = false,
    bypass_validation_limits                                        = false,
    bypass_validation_limits_reason                                 = null,
    laskutettava_yritys_defined                                     = false,
    valvonta$pending                                                = false,
    valvonta$valvoja_id                                             = null
where id = :energiatodistus_id;

