@startuml
actor User

User -> Frontend++: Sign
Frontend -> Backend++: PUT https://localhost:3000/api/private/energiatodistukset/2018/2
note left of Backend
 Save validated pdf
end note
Frontend <- Backend--: 200 OK
alt with mpollux
Frontend -> Mpollux++#Yellow: GET https://localhost:53952/version
note left of Mpollux
Healthcheck Mpollux
end note
Frontend <- Mpollux--: 200 OK
else with kms
note right of Frontend
No need to healthcheck
end note
end
Frontend -> Backend++: POST https://localhost:3000/api/private/energiatodistukset/2018/2/signature/start
note left of Backend
Put ET into signing state
end note
Frontend <- Backend--: 200 OK
Frontend -> Backend++: GET https://localhost:3000/api/private/energiatodistukset/2018/2/signature/digest/fi
note left of Backend
Get the digest of the pdf (backend puts the metadata in place here)
end note
Frontend <- Backend--: 200 OK \n\
{ \n\
    "digest": "MVwwDwYJKoZIhvcv...", \n\
}
alt with mpollux
Frontend -> Mpollux++: OPTIONS https://localhost:53952/sign
Frontend <- Mpollux--: 200 OK
note right of Frontend
Send the digest to Mpollux
end note
Frontend -> Mpollux++#Red: POST https://localhost:53952/sign \n\
{ \n\
    ..., \n\
    "content": "MVwwDwYJKoZIhvcv..." \n\
}
note left of Backend
Get the signature and certificate chain from Mpollux
end note
Frontend <- Mpollux--: 200 OK \n\
  { \n\
      ..., \n\
      "signature": "IAMcrYCDq...", \n\
      "chain": [ \n\
          "MIIDXjCCAkYCCQCSRxcs...", \n\
          "MIIDXjCCAkYCCQCSRxcs...", \n\
          "MIIDXjCCAkYCCQCSRxcs..." \n\
      ], \n\
      ... \n\
  }
else with kms
Frontend -> Backend++#Green: POST https://localhost:3000/api/private/energiatodistukset/2018/2/signature/sign/fi \n\
{ \n\
    ..., \n\
    "content": "MVwwDwYJKoZIhvcv..." \n\
}
note left of Backend
Get the signature and certificate chain from Backend
end note
Backend -> KMS++: solita.etp.service.sign/sign
note left of KMS
Sign the digest
end note
Backend <- KMS--
Frontend <- Backend--: 200 OK \n\
  { \n\
      ..., \n\
      "signature": "IAMcrYCDq...", \n\
      "chain": [ \n\
          "MIIDXjCCAkYCCQCSRxcs...", \n\
          "MIIDXjCCAkYCCQCSRxcs...", \n\
          "MIIDXjCCAkYCCQCSRxcs..." \n\
      ], \n\
      ... \n\
  }
end
Frontend -> Backend++: PUT https://localhost:3000/api/private/energiatodistukset/2018/2/signature/pdf/fi \n\
  { \n\
      "signature": "IAMcrYCDq...", \n\
      "chain": [ \n\
          "MIIDXjCCAkYCCQCSRxcs...", \n\
          "MIIDXjCCAkYCCQCSRxcs...", \n\
          "MIIDXjCCAkYCCQCSRxcs..." \n\
      ], \n\
  }
note left of Backend
Here the signed PDF is created
end note
Frontend <- Backend--: 200 OK
Frontend -> Backend++: POST https://localhost:3000/api/private/energiatodistukset/2018/2/signature/finish
Frontend <- Backend--: 200 OK
User <- Frontend--: Done



@enduml