#!/usr/bin/env bash
# A key and certificates that are known to work have been generated by `generage-key-and-certificates.sh`.
# This script uses them instead of generating new ones.

set -euxo pipefail

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

DEFAULTS_DIR="${SCRIPT_DIR}/default-key-and-certs"

DEFAULT_FILE_SEED="${DEFAULTS_DIR}/default-seed.yaml"
DEFAULT_CRT_FILE_ROOT="${DEFAULTS_DIR}/default-root.pem.crt"
DEFAULT_CRT_FILE_INT="${DEFAULTS_DIR}/default-int.pem.crt"
DEFAULT_CRT_FILE_LEAF="${DEFAULTS_DIR}/default-leaf.pem.crt"

# Put the files in place
mkdir -p "${SCRIPT_DIR}/../../etp-backend/src/test/resources/system-signature"
cp "${DEFAULT_CRT_FILE_LEAF}" "${SCRIPT_DIR}/../../etp-backend/src/test/resources/system-signature/local-signing-leaf.pem.crt"
cp "${DEFAULT_CRT_FILE_INT}" "${SCRIPT_DIR}/../../etp-backend/src/test/resources/system-signature/local-signing-int.pem.crt"
cp "${DEFAULT_CRT_FILE_ROOT}" "${SCRIPT_DIR}/../../etp-backend/src/test/resources/system-signature/local-signing-root.pem.crt"
cp "${DEFAULT_FILE_SEED}" "${SCRIPT_DIR}/seed.yaml"
