name: ci

on:
  pull_request:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./etp-backend
    container:
      image: clojure:openjdk-17-tools-deps

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: clojure -M:uberjar

  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./etp-backend
    container:
      image: clojure:openjdk-17-tools-deps

    steps:
      - uses: actions/checkout@v3
      - name: Lint
        run: clojure -M:lint --fail-level error

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Prepare java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@10.3
        with:
          cli: 1.11.1.1273
      - name: Install Libreoffice
        run: sudo apt-get update && sudo apt-get install libreoffice
      - name: Docker Compose
        working-directory: docker
        run: ./start.sh
      - name: Test
        working-directory: etp-backend
        run: clojure -M:dev:test-ci
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: success() || failure()
        with:
         report_paths: 'etp-backend/target/test.xml'