name: nvd-clojure

on:
  schedule:
    - cron: '0 2 * * 1'
  push:
    branches:
      - feature/AE-2442-nvd-check-fail

jobs:
  nvd:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: etp-core/etp-backend
    container:
      image: clojure:openjdk-17-tools-deps

    steps:
      - uses: actions/checkout@v4
      - name: Remove old NVD and OWASP cache
        run: |
          rm -rf ~/.m2/repository/org/owasp/dependency-check-data
          rm -rf ~/.m2/repository/org/owasp/dependency-check
          rm -rf ~/.dependency-check
      - name: Run nvd
        env:
          NVD_API_TOKEN: ${{ secrets.NVD_API_TOKEN }}
        run: ./nvd.sh
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure()
        with:
          report_paths: '**/etp-core/etp-backend/target/nvd/dependency-check-junit.xml'
          check_name: 'Vulnerability report'