name: renovate

on:
  schedule:
    - cron: '10 0/1 * * *' # Start at ten past to avoid rush hour

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.1.11
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
          configurationFile: .github/renovate-bot-config.json
        env:
          LOG_LEVEL: 'debug'
